import {renderAtlas,lightArea,lightStudy} from './atlas.mjs?v=8f2bfa8652b3';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],reduced=matchMedia('(prefers-reduced-motion: reduce)');
const contact=q('#at-contact');qa('[data-contact]').forEach(b=>b.addEventListener('click',()=>contact.showModal()));
qa('dialog').forEach(d=>d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close()}));
function choiceKeys(buttons,choose){buttons.forEach((b,i)=>b.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight'||e.key==='ArrowDown')n=(i+1)%buttons.length;else if(e.key==='ArrowLeft'||e.key==='ArrowUp')n=(i+buttons.length-1)%buttons.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=buttons.length-1;else return;e.preventDefault();buttons[n].focus();choose(n)}))}
if(q('.mh-folio')){
 const track=q('.mh-folio'),panels=qa('.mh-panel'),desktop=matchMedia('(min-width:901px) and (min-height:701px)'),prev=q('#mh-prev'),next=q('#mh-next');let current=0;
 function mark(){q('#mh-count').textContent=`0${current+1} / 04`;prev.disabled=current===0;next.disabled=current===panels.length-1;}
 function go(i){current=Math.max(0,Math.min(panels.length-1,i));const panel=panels[current],behavior=reduced.matches?'instant':'smooth';if(desktop.matches)track.scrollTo({left:panel.offsetLeft-track.offsetLeft,behavior});else panel.scrollIntoView({behavior,block:'start'});history.replaceState(null,'','#'+panel.id);mark();}
 prev.addEventListener('click',()=>go(current-1));next.addEventListener('click',()=>go(current+1));
 track.addEventListener('scroll',()=>{if(desktop.matches){current=Math.round(track.scrollLeft/track.clientWidth);mark()}},{passive:true});
 addEventListener('scroll',()=>{if(!desktop.matches){current=panels.reduce((best,p,i)=>p.getBoundingClientRect().top<innerHeight*.5?i:best,0);mark()}},{passive:true});
 qa('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const i=panels.findIndex(p=>p.id===a.hash.slice(1));if(i>=0){e.preventDefault();go(i)}}));
 desktop.addEventListener('change',()=>{track.scrollLeft=0;current=0;mark()});
 const initial=panels.findIndex(p=>p.id===location.hash.slice(1));if(initial>=0)go(initial);mark();
 const comparison=q('#mh-comparison'),light=q('#mh-light');function reveal(){const value=Number(light.value);comparison.style.setProperty('--reveal',value+'%');q('#mh-light-value').textContent=value+' % Abend';light.setAttribute('aria-valuetext',value+' Prozent Abendansicht');}light.addEventListener('input',reveal);
 let dragging=false;function drag(e){const r=comparison.getBoundingClientRect();light.value=String(Math.round(Math.min(100,Math.max(0,(e.clientX-r.left)/r.width*100))));reveal()}
 comparison.addEventListener('pointerdown',e=>{if(e.button!==0)return;dragging=true;comparison.setPointerCapture(e.pointerId);drag(e)});comparison.addEventListener('pointermove',e=>{if(dragging)drag(e)});comparison.addEventListener('pointerup',()=>dragging=false);comparison.addEventListener('pointercancel',()=>dragging=false);reveal();
 q('[data-mh-evening]').addEventListener('click',()=>{light.value='100';reveal();go(0)});
 const materialButtons=qa('[data-mh-material]'),details=[['NÄHE / BOUCLÉ','Eine Kante, die weich wird.','Die gerundete Polsterung nimmt dem großen Sofa seine Strenge. Die sichtbare Schlinge gibt der hellen Fläche Tiefe.'],['GEWICHT / TRAVERTIN','Eine Fläche mit Erinnerung.','Offene Poren und kleine Einschlüsse bleiben sichtbar. Der Stein setzt dem weichen Polster eine ruhige, feste Kante entgegen.'],['GRUND / EICHE','Unter allem: etwas Lebendiges.','Die Maserung verbindet den Raum, ohne gleichförmig zu sein. Der Teppich nimmt die Sitzgruppe auf; am Rand bleibt das Holz lesbar.']];
 function chooseMaterial(i){materialButtons.forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)));q('#mh-detail').dataset.material=String(i);q('.mh-detail-mark').textContent='0'+(i+1);['#mh-detail-tag','#mh-detail-title','#mh-detail-copy'].forEach((s,j)=>q(s).textContent=details[i][j]);}
 materialButtons.forEach((b,i)=>b.addEventListener('click',()=>chooseMaterial(i)));choiceKeys(materialButtons,chooseMaterial);q('#mh-detail-open').addEventListener('click',()=>q('#mh-image-dialog').showModal());chooseMaterial(0);
}
if(q('#da-model')){
 const sun=q('#da-sun'),aperture=q('#da-aperture'),buttons=qa('[data-atlas-view]'),play=q('#da-play');let view='raum',timer=null,started=0,rotation=0,lift=0;
 function paint(){if(q('#da-rotation-value')){q('#da-rotation-value').textContent=rotation+'°';q('#da-lift-value').textContent=Math.round(lift*100)+' %';q('#da-rotation').disabled=view!=='raum';q('#da-lift').disabled=view!=='raum'}const s=Number(sun.value),a=Number(aperture.value),day=s<32?'Morgen':s>68?'Abend':'Mittag';q('#da-geometry').innerHTML=renderAtlas(s,a,view,rotation,lift);q('#da-sun-value').textContent=day;q('#da-aperture-value').textContent=a+' %';q('#da-area').textContent=(lightArea(s,a)/24*100).toFixed(1).replace('.',',')+' % BODEN IM LICHT';q('#da-model-desc').textContent=`${view==='raum'?'Räumliche Ansicht':view==='grundriss'?'Grundriss':'Schnitt'}, Dachöffnung ${a} Prozent, Sonnenstand ${day}.${view==='raum'?` Blickwinkel ${rotation} Grad, Dach angehoben um ${Math.round(lift*100)} Prozent.`:''}`;sun.setAttribute('aria-valuetext',day);aperture.setAttribute('aria-valuetext',a+' Prozent Öffnungsweite');q('#da-insight').textContent=a<40?'Eine schmale Öffnung setzt einen konzentrierten Lichtakzent.':s<30?'Das Licht rückt an den Rand. Die Mitte bleibt im Schatten.':s>70?'Der Tag zieht weiter. Die Lichtfläche wandert zur offenen Seite.':'Das Licht sammelt sich in der Mitte. Die Ränder bleiben ruhiger.';qa('[data-mini-view]').forEach(svg=>svg.innerHTML=renderAtlas(s,a,svg.dataset.miniView));}
 function stop(){clearInterval(timer);timer=null;play.setAttribute('aria-pressed','false');play.textContent='Den Tag durchlaufen ▷';q('#da-insight').setAttribute('aria-live','polite')}
 function choose(i){const before=q('#da-model').cloneNode(true);const oldView=view;view=buttons[i].dataset.atlasView;buttons.forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)));q('#da-view-label').textContent=['AXONOMETRIE','GRUNDRISS','LÄNGSSCHNITT'][i];paint();if(oldView!==view&&!reduced.matches&&q('#da-model').animate){before.querySelectorAll('[id]').forEach(e=>e.removeAttribute('id'));before.removeAttribute('id');before.removeAttribute('aria-labelledby');before.setAttribute('aria-hidden','true');before.classList.add('da-model-ghost');before.style.width='100%';before.style.height='100%';q('.da-drawing').append(before);const a=before.animate([{opacity:1,transform:'scale(1) rotateX(0deg)'},{opacity:0,transform:'scale(.85) rotateX(38deg)'}],{duration:650,easing:'cubic-bezier(.2,.75,.2,1)'});a.finished.finally(()=>before.remove()).catch(()=>{});q('#da-model').animate([{opacity:0,transform:'scale(1.08)'},{opacity:1,transform:'scale(1)'}],{duration:750})}}
 buttons.forEach((b,i)=>b.addEventListener('click',()=>choose(i)));choiceKeys(buttons,choose);
 qa('[data-open-view]').forEach(a=>a.addEventListener('click',()=>{choose(buttons.findIndex(b=>b.dataset.atlasView===a.dataset.openView))}));
 [sun,aperture].forEach(el=>el.addEventListener('input',()=>{stop();paint()}));
 play.addEventListener('click',()=>{if(timer){stop();return}sun.value='0';paint();play.textContent='Tageslauf pausieren Ⅱ';play.setAttribute('aria-pressed','true');q('#da-insight').setAttribute('aria-live','off');started=performance.now();timer=setInterval(()=>{sun.value=String(Math.min(100,Math.round((performance.now()-started)/100)));paint();if(Number(sun.value)>=100)stop()},reduced.matches?1000:100)});
 q('#da-reset').addEventListener('click',()=>{stop();sun.value='45';aperture.value='65';rotation=0;lift=0;if(q('#da-rotation')){q('#da-rotation').value='0';q('#da-lift').value='0'}choose(0)});
 if(q('#da-rotation')){
  const turn=q('#da-rotation'),raise=q('#da-lift'),drawing=q('.da-drawing');let drag=null;
  const set=()=>{stop();rotation=Number(turn.value);lift=Number(raise.value)/100;paint()};turn.addEventListener('input',set);raise.addEventListener('input',set);
  drawing.addEventListener('pointerdown',e=>{if(e.button!==0||view!=='raum')return;drag={x:e.clientX,y:e.clientY,rotation,lift};drawing.setPointerCapture(e.pointerId)});
  drawing.addEventListener('pointermove',e=>{if(!drag)return;turn.value=String(Math.round(Math.max(-30,Math.min(30,drag.rotation+(e.clientX-drag.x)*.13))));raise.value=String(Math.round(Math.max(0,Math.min(100,drag.lift*100-(e.clientY-drag.y)*.3))));set()});
  ['pointerup','pointercancel','lostpointercapture'].forEach(t=>drawing.addEventListener(t,()=>drag=null));drawing.addEventListener('dragstart',e=>e.preventDefault());
  drawing.addEventListener('keydown',e=>{if(view!=='raum')return;const key=e.key;if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(key))return;e.preventDefault();if(key==='ArrowLeft'||key==='ArrowRight')turn.value=String(Math.max(-30,Math.min(30,Number(turn.value)+(key==='ArrowRight'?3:-3))));else raise.value=String(Math.max(0,Math.min(100,Number(raise.value)+(key==='ArrowUp'?5:-5))));set()});
 }
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});window.addEventListener('pagehide',stop);reduced.addEventListener('change',stop);
 const observer=new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)stop()},{threshold:.05});observer.observe(q('.da-work'));paint();
}
if(q('#al-instrument'))import('./sound-room.mjs?v=3473e72f5f59');
qa('.at-preview-room').forEach(preview=>{const card=preview.closest('a');card.addEventListener('pointermove',e=>{const r=preview.getBoundingClientRect();preview.style.setProperty('--preview-light',Math.round(Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))*100)+'%')});card.addEventListener('pointerleave',()=>preview.style.removeProperty('--preview-light'));card.addEventListener('focus',()=>preview.style.setProperty('--preview-light','85%'));card.addEventListener('blur',()=>preview.style.removeProperty('--preview-light'));});
