(()=>{'use strict';
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const contact=document.querySelector('#contact-dialog');
document.querySelectorAll('[data-contact]').forEach(b=>b.addEventListener('click',()=>contact?.showModal()));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
document.querySelectorAll('dialog').forEach(dialog=>{dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()});dialog.addEventListener('close',()=>{if(!document.querySelector('dialog[open]'))document.body.style.overflow=''})});
const gallery=document.querySelector('.photo-gallery');
if(gallery){const views=[...document.querySelectorAll('[data-gallery-view]')];views.forEach(b=>b.addEventListener('click',()=>{gallery.dataset.view=b.dataset.galleryView;views.forEach(x=>x.setAttribute('aria-pressed',String(x===b)))}));
const dialog=document.querySelector('#image-dialog'),image=document.querySelector('#selected-image');
const items=[{src:'assets/elena-coast.webp',title:'Am Rand der Stille',alt:'Eine kleine Figur an einer dunklen Küste mit silbrigem Meer.',copy:'Eine Figur. Viel Weite. Eine Begegnung mit der Stille.'},{src:'assets/elena-glass.webp',title:'Licht bleibt',alt:'Orangefarbenes Glas wirft Licht auf eine ultramarinblaue Oberfläche.',copy:'Eine Farbe setzt sich fort. Im Material. Im Licht. Im Schatten.'},{src:'assets/elena-coast.webp',title:'Ein zweiter Blick',alt:'Vergrößerter monochromer Ausschnitt der Küstenstudie.',copy:'Ein Ausschnitt aus Studie 01. Weniger Kontext, eine andere Spannung.'}];let current=0,opener=null;
function show(index){current=(index+items.length)%items.length;const item=items[current];image.src=item.src;image.alt=item.alt;image.parentElement.classList.toggle('is-detail',current===2);document.querySelector('#image-title').textContent=item.title;document.querySelector('#image-description').textContent=item.copy;document.querySelector('#image-counter').textContent=String(current+1).padStart(2,'0')+' / 03'}
document.querySelectorAll('[data-image]').forEach(b=>b.addEventListener('click',()=>{opener=b;show(Number(b.dataset.image));dialog.showModal();document.body.style.overflow='hidden'}));document.querySelector('#image-previous').addEventListener('click',()=>show(current-1));document.querySelector('#image-next').addEventListener('click',()=>show(current+1));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();show(current-1)}if(e.key==='ArrowRight'){e.preventDefault();show(current+1)}});dialog.addEventListener('close',()=>opener?.focus({preventScroll:true}));}
const exhibit=document.querySelector('#arch-exhibit');
if(exhibit){const viewButtons=[...document.querySelectorAll('[data-arch-view]')];viewButtons.forEach(b=>b.addEventListener('click',()=>{exhibit.dataset.view=b.dataset.archView;viewButtons.forEach(x=>x.setAttribute('aria-pressed',String(x===b)))}));
const topics=[['Der Landschaft zuhören.','Die Weite des Wassers und der geschützte Rücken des Gebäudes erzeugen zwei unterschiedliche Qualitäten. Der Entwurf hält beides zusammen.'],['Eine Öffnung verändert alles.','Licht gibt dem Raum einen Rhythmus. Tiefe Laibungen fassen den Blick und lassen zwischen hellem Außenraum und geschütztem Innenraum einen Übergang entstehen.'],['Wenige Materialien. Klare Beziehungen.','Heller Beton, Glas und Wasser tragen die Idee. Ihre unterschiedlichen Oberflächen machen das wechselnde Licht sichtbar, ohne miteinander zu konkurrieren.']];const tabs=[...document.querySelectorAll('[data-arch-topic]')];tabs.forEach((b,i)=>b.addEventListener('click',()=>{tabs.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelector('#arch-topic-title').textContent=topics[i][0];document.querySelector('#arch-topic-copy').textContent=topics[i][1]}));
let frame=0,x=0,y=0;const fine=matchMedia('(hover: hover) and (pointer: fine)');const paint=()=>{frame=0;exhibit.style.setProperty('--arch-x',x+'deg');exhibit.style.setProperty('--arch-y',y+'deg')};exhibit.addEventListener('pointermove',e=>{if(reduced.matches||!fine.matches||e.target.closest('button'))return;const r=exhibit.getBoundingClientRect();x=((e.clientX-r.left)/r.width-.5)*2.5;y=((e.clientY-r.top)/r.height-.5)*-1.5;if(!frame)frame=requestAnimationFrame(paint)},{passive:true});const reset=()=>{cancelAnimationFrame(frame);frame=0;x=y=0;paint()};exhibit.addEventListener('pointerleave',reset);reduced.addEventListener('change',reset);document.addEventListener('visibilitychange',()=>{if(document.hidden)reset()});}
})();
