(()=>{
const dialog=document.querySelector('#contact-dialog');
document.querySelectorAll('[data-contact]').forEach(b=>b.addEventListener('click',()=>dialog.showModal()));
dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close()});
const content={
property:{leben:['Ankommen im Quartier.','Ein Haus beginnt nicht an der Haustür. Die Wege zum Wasser, die Nachbarschaft und die kleinen Orte des Alltags prägen das Gefühl von Zuhause.'],raum:['Platz für eigene Vorstellungen.','Licht, Raumfolgen und die Verbindung zwischen den Zimmern prägen den Charakter. Wir schauen darauf, welche Möglichkeiten zu Ihren Bedürfnissen passen.'],weg:['Eine Entscheidung mit Überblick.','Welche Informationen fehlen noch? Welche Fragen gehören in die nächste Besichtigung? Ein klarer Ablauf schafft Raum für eine bewusste Entscheidung.']},
decision:{richtung:['Eine Richtung, die Auswahl ermöglicht.','Wir klären Ziele und bewerten Handlungsfelder. Am Ende steht eine nachvollziehbare Priorität – und auch eine bewusste Entscheidung, was vorerst warten kann.'],rollen:['Verantwortung, die im Alltag greifbar wird.','Wir betrachten Schnittstellen, Rollen und Entscheidungswege. Ziel ist ein gemeinsames Verständnis davon, wer etwas voranbringt und wer dafür einbezogen werden muss.'],wirkung:['Ein nächster Schritt, der wirklich stattfindet.','Wir übersetzen Vorhaben in überschaubare Arbeitsschritte. Regelmäßige Rückblicke machen sichtbar, was funktioniert und wo die Zusammenarbeit angepasst werden sollte.']},
material:{eiche:['Wärme, die mit dem Alltag lebt.','Helle Eiche gibt dem Raum eine ruhige Grundlage. Dazu passen weiche Textilien und einzelne dunkle Akzente.'],leinen:['Leichtigkeit mit spürbarer Struktur.','Leinen bringt eine weiche Unregelmäßigkeit in den Raum. In Verbindung mit hellen Flächen und warmen Naturtönen entsteht eine entspannte Stimmung.'],kalk:['Ruhe, die das Licht verändert.','Eine matte, mineralische Oberfläche lässt Licht weich erscheinen. Holz und dunkle Einzelstücke geben der zurückhaltenden Palette Tiefe.']},
rhythm:{voll:['Ein kleiner Platz im vollen Kalender.','Wir schauen zuerst darauf, welche Zeitfenster tatsächlich dir gehören. Ein guter Einstieg muss zu deinem Alltag passen und darf überschaubar bleiben.'],start:['Neugier statt großer Versprechen.','Was möchtest du ausprobieren? Was hat dir früher Freude gemacht? Daraus kann ein erster gemeinsamer Schritt entstehen, der sich nach dir anfühlt.'],wechsel:['Ein Rahmen, der beweglich bleibt.','Wir sprechen darüber, was trotz wechselnder Wochen verlässlich ist. So lässt sich ein Einstieg finden, der Spielraum hat und dir Orientierung gibt.']}
};
document.querySelectorAll('[data-switch]').forEach(group=>{group.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{const key=group.dataset.switch,v=content[key][b.dataset.key],target=document.querySelector('#'+key+'-copy');group.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));target.querySelector('h3').textContent=v[0];target.querySelector('p').textContent=v[1];if(key==='material')document.querySelector('.mh-mood').dataset.material=b.dataset.key;if(key==='decision')target.querySelector('.eyebrow').textContent={richtung:'STRATEGIE',rollen:'ORGANISATION',wirkung:'UMSETZUNG'}[b.dataset.key];}));});
const task=document.querySelector('#demo-task');if(task){let step=0;const next=document.querySelector('#task-next'),status=document.querySelector('#board-status');const render=()=>{document.querySelector('[data-column="'+step+'"]').append(task);next.textContent=['In Arbeit nehmen →','Als erledigt markieren →','Abgeschlossen ✓'][step];next.disabled=step===2;status.textContent=['Die Aufgabe wartet auf ihren ersten Schritt.','Die Aufgabe ist jetzt in Arbeit.','Die Beispielaufgabe ist abgeschlossen. Mit Zurücksetzen beginnt die Demo erneut.'][step]};next.addEventListener('click',()=>{step=Math.min(2,step+1);render()});document.querySelector('#board-reset').addEventListener('click',()=>{step=0;render()});}
})();
