// Shared deterministic state for the interactive studies. No network or storage.
export const clamp=(v,min=0,max=1)=>Math.max(min,Math.min(max,Number(v)));
export const initialFeedback=[
 {id:1,text:'Der Kontaktknopf ist am Handy schwer zu finden.',category:'funktion',priority:3},
 {id:2,text:'Die Projektbeschreibung könnte konkreter sein.',category:'inhalt',priority:2},
 {id:3,text:'Der Kontrast der kleinen Beschriftung ist zu schwach.',category:'gestaltung',priority:3},
 {id:4,text:'Beim Zurückgehen geht die Auswahl verloren.',category:'funktion',priority:3},
 {id:5,text:'Ein Beispiel würde die Leistung verständlicher machen.',category:'inhalt',priority:2},
 {id:6,text:'Zwischen den Bildern fehlt etwas Raum.',category:'gestaltung',priority:1}
];
export const categoryNames={funktion:'Funktion',inhalt:'Inhalt',gestaltung:'Gestaltung'};
export function groupFeedback(items){return Object.keys(categoryNames).map(key=>({key,name:categoryNames[key],items:items.filter(i=>i.category===key)}))}
export function orderedFeedback(items,filter='all'){return items.filter(i=>filter==='all'||i.category===filter).map((v,i)=>({...v,index:i})).sort((a,b)=>b.priority-a.priority||a.index-b.index)}
export function classifyFeedback(text){const t=text.toLowerCase();return /klick|button|knopf|handy|fehler|funktion|laden|zurück|filter|suche|speichern|absturz|navigation/.test(t)?'funktion':/farbe|bild|schrift|abstand|kontrast|layout/.test(t)?'gestaltung':'inhalt'}
export const decisions={
 tempo:{title:'Ein kleiner Start.\nFrühe Erkenntnisse.',copy:'Ein enger Umfang macht einen frühen Versuch möglich. Dafür bleiben manche Wünsche zunächst offen.',commitment:'Wir begrenzen den ersten Versuch auf eine klar beschriebene Aufgabe.',tradeoff:'Ein schneller Start liefert früheres Feedback, aber noch keine vollständige Lösung.',sequence:['versuch','konzept','abstimmung']},
 qualitaet:{title:'Eine klare Grundlage.\nBewusst später starten.',copy:'Mehr Zeit für Annahmen und Gestaltung senkt vermeidbare Unklarheit. Dafür erfahren wir später, wie das Angebot im Alltag ankommt.',commitment:'Wir prüfen das Konzept zuerst an konkreten Anforderungen.',tradeoff:'Mehr Ausarbeitung schafft Tiefe, verschiebt aber den ersten Kontakt mit Nutzern.',sequence:['konzept','abstimmung','versuch']},
 team:{title:'Eine gemeinsame Richtung.\nGeteilte Verantwortung.',copy:'Das Team klärt Erwartungen und Zuständigkeiten vor dem Start. Das braucht Gesprächszeit und macht die spätere Zusammenarbeit verbindlicher.',commitment:'Wir benennen Entscheidungswege und Verantwortliche vor dem ersten Versuch.',tradeoff:'Frühe Abstimmung stärkt Zusammenarbeit, bindet jedoch Zeit vor dem Start.',sequence:['abstimmung','versuch','konzept']}
};
const steps={versuch:{title:'Einen kleinen Versuch machen',copy:'Eine eng umrissene Idee mit wenigen Personen ausprobieren.'},konzept:{title:'Die Annahmen sichtbar machen',copy:'Nutzen, Umfang und Voraussetzungen auf einer Seite festhalten.'},abstimmung:{title:'Verantwortung gemeinsam klären',copy:'Entscheider, Beteiligte und Rückmeldeschleifen benennen.'}};
const questions={nutzen:{label:'Wer braucht dieses Angebot?',copy:'Drei Gespräche mit möglichen Nutzern vorbereiten.',first:'versuch'},machbarkeit:{label:'Was können wir verlässlich liefern?',copy:'Die schwierigste Voraussetzung in einem kleinen Prototyp prüfen.',first:'konzept'},verantwortung:{label:'Wer darf welche Entscheidung treffen?',copy:'Zuständigkeiten für Umfang, Termin und Rückmeldungen festhalten.',first:'abstimmung'}};
export function decisionPlan(priority='tempo',question='nutzen'){const d=decisions[priority]||decisions.tempo,q=questions[question]||questions.nutzen;const order=[q.first,...d.sequence.filter(x=>x!==q.first)];return {...d,question:q.label,next:q.copy,steps:order.map(k=>({...steps[k],key:k}))}}
export const reflectorPresets=[[[.25,.28],[.73,.34],[.60,.77]],[[.15,.19],[.84,.24],[.81,.78]],[[.28,.48],[.73,.2],[.5,.79]]];
export const reflectionMaterials=[{name:'Glas',gain:.62,cutoff:11000,copy:'Glas lässt einen hellen, klaren Nachklang zurück.'},{name:'Holz',gain:.43,cutoff:3500,copy:'Holz gibt dem Nachklang einen weicheren, dunkleren Ton.'},{name:'Filz',gain:.14,cutoff:1100,copy:'Filz nimmt Energie auf. Die Antwort wird leiser und kürzer.'}];
export function reflectionPath(position,material=0){const [x,y]=position,m=reflectionMaterials[clamp(material,0,2)],source=[.43,.48],listener=[.55,.68];const length=Math.hypot(x-source[0],y-source[1])+Math.hypot(x-listener[0],y-listener[1]);return {length,delay:.055+length*.38,gain:m.gain/(1+length*2),cutoff:m.cutoff,pan:clamp((x-.5)*1.7,-1,1)}}
export const roomChapters=[{name:'ANKOMMEN',cut:28,material:'STEIN / DER ERSTE SCHRITT',title:'Ankommen.\nDen Alltag ablegen.',copy:'Eine kleine Schwelle gibt Orientierung. Die Bank am Eingang ist ein Ort für Schuhe, Tasche und einen ersten Moment Ruhe.'},{name:'ZUSAMMENLEBEN',cut:58,material:'EICHE / OFFENE MITTE',title:'Platz für das\ngemeinsame Leben.',copy:'Eine lange Mitte hält den Raum offen. Der Tisch wird zum Treffpunkt, das Licht verbindet die unterschiedlichen Nutzungen.'},{name:'RÜCKZUG',cut:86,material:'TEXTIL / EIN RUHIGER RAND',title:'Ein Ort,\nder nichts verlangt.',copy:'Am Ende des Weges wird der Raum leiser. Eine geschützte Nische und ein tiefer Sitz lassen Abstand zum Alltag entstehen.'}];
export function roomForCut(value){return value<43?0:value<74?1:2}
export const materials=[{name:'Leinen',title:'Weich, ohne\nbeliebig zu sein.',copy:'Das Leinen nimmt dem klaren Raum die Strenge. Seine offene Struktur lebt vom Licht und lädt zum Bleiben ein.',origin:'53% 50%'},{name:'Naturstein',title:'Ein ruhiger\nSchwerpunkt.',copy:'Der Stein gibt der Mitte Gewicht. Kleine Poren und leise Unregelmäßigkeiten machen seine Oberfläche lebendig.',origin:'93% 55%'},{name:'Eiche',title:'Wärme, die\nden Raum hält.',copy:'Das Holz verbindet den Boden mit den kleinen Dingen des Alltags. Seine Maserung bringt Richtung, ohne laut zu werden.',origin:'8% 45%'}];
export const photoWorks=[{asset:'elena-coast.webp',title:'Am Rand der Stille'},{asset:'elena-surf.webp',title:'Was wiederkehrt'},{asset:'elena-glass.webp',title:'Licht bleibt kurz'},{"asset": "elena-04-sea-mist-dunes.webp", "title": "Was der Nebel hält"},{"asset": "elena-05-tidal-pool.webp", "title": "Ein Himmel im Stein"},{"asset": "elena-06-frosted-glass.webp", "title": "Die Haut des Lichts"},{"asset": "elena-07-linen-curtain.webp", "title": "Zwischen innen und außen"},{"asset": "elena-08-silver-seawater.webp", "title": "Die Zeit an der Kante"}];
export const diningChapters=[{time:'19:00 / ANKOMMEN',chapter:'01 / DER ANFANG',title:'Ein Tisch.\nViele Möglichkeiten.',copy:'Gläser fangen das letzte Licht. Eine Serviette wartet. Der Abend hat noch Platz für alles.',action:'Den ersten Gang servieren →',alt:'Der gedeckte Tisch vor dem ersten Gang'},{time:'19:30 / GENIESSEN',chapter:'02 / DAS ZUSAMMENKOMMEN',title:'Ein erster Bissen.\nDas Gespräch beginnt.',copy:'Rote Bete, eine weiche Creme, frische Kräuter. Der erste Gang gibt eine Richtung vor und lässt den Abend in seinen eigenen Takt finden.',action:'Zum süßen Abschluss →',alt:'Derselbe Tisch mit einem ersten Gang aus roter Bete und Creme'},{time:'21:00 / BLEIBEN',chapter:'03 / DER NACHKLANG',title:'Das Beste bleibt\nnoch ein wenig.',copy:'Eine Birne, etwas Süße und Zeit. Auf dem Tuch stehen die kleinen Spuren eines Abends, der nicht nach der Uhr fragt.',action:'Noch einmal Platz nehmen ↺',alt:'Der Tisch zum Dessert mit Birne und Spuren des Abends'}];
export const menus=[{name:'Garten',courses:[['Zum Anfang','Rote Bete','Creme, Kräuteröl, geröstete Kerne'],['In der Mitte','Sellerie aus dem Ofen','Apfel, Haselnuss, braune Butter'],['Zum Schluss','Birne & Vanille','Joghurt, Mandel, warmer Sud']]},{name:'Küste',courses:[['Zum Anfang','Fenchel & Zitrus','Dill, Olivenöl, Meersalz'],['In der Mitte','Fisch aus der Pfanne','Kartoffel, Lauch, Zitronenbutter'],['Zum Schluss','Zitrone & Baiser','Sahne, knusprige Mandel']]},{name:'Abendlicht',courses:[['Zum Anfang','Tomate & Pfirsich','Basilikum, Ricotta, Sauerteig'],['In der Mitte','Ravioli','Spinat, Salbei, Parmesan'],['Zum Schluss','Dunkle Schokolade','Kirsche, Crumble, Meersalz']]}];
