(()=>{'use strict';
const q=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],reduced=matchMedia('(prefers-reduced-motion: reduce)'),fine=matchMedia('(hover:hover) and (pointer:fine)');
const runs=new WeakMap();function animate(el,frames,options={}){if(!el||reduced.matches||!el.animate)return;const prior=runs.get(el);prior?.cancel();const run=el.animate(frames,{duration:650,easing:'cubic-bezier(.2,.75,.2,1)',...options});runs.set(el,run);return run}
document.body.classList.add('m8-enhanced');
if(q('#deck-next')){
 const deck=q('#kollektion'),cards=all('.collection-card'),names=['Claras','Jonas’','Milas','Leons','Noras','Elenas','Davids','Sofias','Matteos','Adas'];let current=0,drag=null,moved=false,grid=false;
 function paint(offset=0){cards.forEach((card,i)=>{const n=i-current,visible=Math.abs(n)<=2;card.style.setProperty('--deck-x',(n*card.clientWidth*.65+offset*.65)+'px');card.style.setProperty('--deck-z',(-Math.abs(n)*180)+'px');card.style.setProperty('--deck-r',(-Math.max(-2,Math.min(2,n))*24)+'deg');card.style.setProperty('--deck-o',visible?String(1-Math.abs(n)*.28):'0');card.style.zIndex=String(10-Math.abs(n));card.style.visibility=grid||visible?'visible':'hidden';card.tabIndex=grid||n===0?0:-1;card.setAttribute('aria-current',String(n===0));});q('#deck-count').textContent=String(current+1).padStart(2,'0')+' / 10';q('#deck-prev').disabled=current===0;q('#deck-next').disabled=current===9;q('#deck-enter').href=cards[current].getAttribute('href');q('#deck-enter').innerHTML=names[current]+' Welt betreten <span>↗</span>';deck.dataset.active=String(current)}
 function go(i){current=Math.max(0,Math.min(9,i));paint()}
 q('#deck-prev').addEventListener('click',()=>go(current-1));q('#deck-next').addEventListener('click',()=>go(current+1));
 cards.forEach((card,i)=>card.addEventListener('click',e=>{if(grid)return;if(moved){e.preventDefault();moved=false;return}if(i!==current){e.preventDefault();go(i)}}));
 deck.addEventListener('keydown',e=>{if(grid)return;const n={ArrowRight:current+1,ArrowLeft:current-1,Home:0,End:9}[e.key];if(n!==undefined){e.preventDefault();go(n);cards[current].focus({preventScroll:true})}});
 deck.addEventListener('pointerdown',e=>{if(grid||e.button!==0)return;drag={x:e.clientX,y:e.clientY,id:e.pointerId};moved=false});
 deck.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)>9&&Math.abs(dx)>Math.abs(dy)){moved=true;deck.classList.add('is-dragging');deck.setPointerCapture(e.pointerId);paint(dx)}});
 function finish(e){if(!drag)return;const dx=e.clientX-drag.x;drag=null;deck.classList.remove('is-dragging');if(moved&&Math.abs(dx)>45)go(current+(dx<0?1:-1));else paint();setTimeout(()=>moved=false,0)}
 deck.addEventListener('pointerup',finish);deck.addEventListener('pointercancel',()=>{drag=null;deck.classList.remove('is-dragging');paint()});deck.addEventListener('dragstart',e=>e.preventDefault());
 q('#deck-mode').addEventListener('click',()=>{grid=!grid;deck.classList.toggle('is-grid',grid);q('#deck-mode').setAttribute('aria-pressed',String(grid));q('#deck-mode').textContent=grid?'Zur räumlichen Auswahl':'Alle auf einen Blick';paint();animate(deck,[{opacity:.35,transform:'translateY(25px)'},{opacity:1,transform:'none'}])});
 addEventListener('resize',()=>paint());paint();requestAnimationFrame(()=>requestAnimationFrame(()=>deck.classList.add('m8-ready')));
}
// Shared gesture mechanics; each page chooses its own movement and destination.
function watch(el,attr,fn){if(!el)return;let old=el.getAttribute(attr);new MutationObserver(()=>{const next=el.getAttribute(attr);if(next!==old){const before=old;old=next;fn(next,before)}}).observe(el,{attributes:true,attributeFilter:[attr]})}
function swipe(el,read,change,preview){let drag=null,suppressUntil=0;
 el.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button,input,a'))return;drag={x:e.clientX,y:e.clientY,start:read(),horizontal:false}});
 el.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(!drag.horizontal&&Math.abs(dy)>Math.abs(dx)+10){drag=null;return}if(Math.abs(dx)>10){drag.horizontal=true;el.setPointerCapture(e.pointerId);el.classList.add('is-dragging');preview?.(dx)}});
 el.addEventListener('pointerup',e=>{if(!drag)return;const dx=e.clientX-drag.x;if(drag.horizontal){suppressUntil=performance.now()+350;if(Math.abs(dx)>42)change(drag.start+(dx<0?1:-1))}drag=null;el.classList.remove('is-dragging');preview?.(0)});
 for(const type of ['pointercancel','lostpointercapture'])el.addEventListener(type,()=>{drag=null;el.classList.remove('is-dragging');preview?.(0)});
 el.addEventListener('click',e=>{if(performance.now()<suppressUntil){e.preventDefault();e.stopImmediatePropagation()}},{capture:true});el.addEventListener('dragstart',e=>e.preventDefault());
}
function keysAt(el,read,choose,max){el.addEventListener('keydown',e=>{if(e.target!==el)return;const v={ArrowRight:read()+1,ArrowLeft:read()-1,Home:0,End:max}[e.key];if(v!==undefined){e.preventDefault();choose(Math.max(0,Math.min(max,v)))}})}
if(q('.cw-book')){
 const book=q('.cw-book'),photo=q('.cw-photo');
 function snapshot(){const copy=book.cloneNode(true);copy.querySelectorAll('.m8-paper').forEach(x=>x.remove());copy.querySelectorAll('[id]').forEach(x=>x.removeAttribute('id'));copy.querySelectorAll('[tabindex]').forEach(x=>x.removeAttribute('tabindex'));copy.className='cw-book m8-paper';copy.setAttribute('aria-hidden','true');copy.inert=true;return copy}
 let saved=snapshot();
 watch(book,'data-page',(next,old)=>{book.querySelectorAll('.m8-paper').forEach(x=>x.remove());const outgoing=saved;saved=snapshot();if(reduced.matches)return;book.append(outgoing);const forward=Number(next)>Number(old);outgoing.style.transformOrigin=forward?'left center':'right center';const run=animate(outgoing,[{transform:'rotateY(0deg)',opacity:1},{transform:`rotateY(${forward?-108:108}deg)`,opacity:.05}],{duration:850});run?.finished.finally(()=>outgoing.remove()).catch(()=>{});animate(q('.cw-caption'),[{opacity:0,transform:'translateY(14px)'},{opacity:1,transform:'none'}],{delay:120,duration:650})});
 const read=()=>Number(book.dataset.page),choose=i=>q(`[data-cw-page="${Math.max(0,Math.min(2,i))}"]`).click();swipe(photo,read,choose,dx=>{if(!reduced.matches)book.style.setProperty('--book-pull',Math.max(-12,Math.min(12,dx/25))+'deg')});keysAt(photo,read,choose,2);
}
if(q('#jb-thought')){
 const field=q('.network-field'),panel=q('#jb-thought'),nodes=all('.network-node');let opener;
 const themes=[['STRATEGIE','Eine Richtung macht Möglichkeiten sichtbar.','Welche Entscheidung bringt uns weiter? Wir beginnen mit dem Ziel und betrachten dann die Wege, die wirklich dorthin führen.'],['ORGANISATION','Verantwortung braucht einen klaren Platz.','An den Schnittstellen entstehen die interessantesten Fragen. Wir machen sichtbar, wer entscheidet, wer beiträgt und was dafür gebraucht wird.'],['UMSETZUNG','Der nächste Schritt muss greifbar sein.','Aus einer Richtung wird ein Arbeitsrhythmus. Kleine überprüfbare Schritte geben einer Entscheidung Wirkung im Alltag.'],['PERSPEKTIVEN','Ein guter Gedanke kommt selten allein.','Rennrad, Kochen, Zeitgeschichte. Andere Blickwinkel helfen mir, vertraute Zusammenhänge neu zu lesen.'],['KLARHEIT','Eine präzise Frage verändert das Gespräch.','Ich höre zu, bis wir das eigentliche Thema benennen können. Oft wird danach eine Entscheidung einfacher.'],['AUSTAUSCH','Was beschäftigt Sie gerade?','Ein erstes Gespräch beginnt mit Ihrem Blick auf die Situation. Dafür braucht es noch kein fertiges Projekt.']];
 function close(){panel.hidden=true;field.classList.remove('is-exploring');nodes.forEach(n=>n.removeAttribute('aria-expanded'));opener?.focus({preventScroll:true})}
 nodes.forEach((node,i)=>node.addEventListener('click',e=>{e.preventDefault();opener=node;const t=themes[i];q('#jb-thought-index').textContent='0'+(i+1)+' / '+t[0];q('#jb-thought-title').textContent=t[1];q('#jb-thought-copy').textContent=t[2];q('#jb-thought-link').href=node.getAttribute('href');panel.hidden=false;field.classList.add('is-exploring');node.setAttribute('aria-expanded','true');panel.focus({preventScroll:true});animate(panel,[{opacity:0,transform:'translate(-45%,-50%) rotateY(-14deg)'},{opacity:1,transform:'translate(-50%,-50%) rotateY(0deg)'}],{duration:650})}));
 q('#jb-thought-close').addEventListener('click',close);panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();close()}});q('#jb-thought-link').addEventListener('click',()=>{panel.hidden=true;field.classList.remove('is-exploring')});
}
if(q('.mh-folio')){
 const points=all('[data-room-detail]'),track=q('.mh-folio'),chapters=all('.m8-room-chapters a'),panels=all('.mh-panel');
 points.forEach(b=>{b.addEventListener('pointerdown',e=>e.stopPropagation());b.addEventListener('click',()=>{q(`[data-mh-material="${b.dataset.roomDetail}"]`).click();chapters[1].click();const title=q('#mh-detail-title');title.tabIndex=-1;title.focus({preventScroll:true});animate(q('#mh-detail'),[{clipPath:'inset(0 100% 0 0)'},{clipPath:'inset(0 0% 0 0)'}],{duration:950,delay:180})})});
 function mark(){let i=0;if(innerWidth>900&&innerHeight>700)i=Math.round(track.scrollLeft/track.clientWidth);else{i=panels.reduce((best,p,j)=>p.getBoundingClientRect().top<innerHeight*.5?j:best,0)}chapters.forEach((a,j)=>a.setAttribute('aria-current',String(i===j)))}
 track.addEventListener('scroll',mark,{passive:true});addEventListener('scroll',mark,{passive:true});mark();
 watch(q('#mh-detail'),'data-material',()=>animate(q('.mh-material-note'),[{opacity:0,transform:'translateX(18px)'},{opacity:1,transform:'none'}]));
}
if(q('#lw-demo')){
 const demo=q('#lw-demo'),paper=q('.lw-receipt'),read=()=>Number(demo.dataset.step),choose=i=>q(`[data-flow-step="${Math.max(0,Math.min(2,i))}"]`).click();
 swipe(paper,read,i=>choose(read()-(i-read())),dx=>{paper.style.transform=dx?`translateX(${Math.max(-85,Math.min(85,dx*.6))}px) rotate(${dx/35}deg)`:''});keysAt(paper,read,choose,2);
 watch(demo,'data-step',(next,old)=>{const direction=Number(next)>Number(old)?1:-1;animate(paper,[{opacity:.45,transform:`translateX(${-direction*65}px) rotate(${-direction*8}deg) rotateY(${-direction*15}deg)`},{opacity:1,transform:`translateX(${Number(next)*20}px) rotate(0deg) rotateY(0deg)`}],{duration:750});animate(q('.receipt-symbol'),[{transform:'scale(.5) rotate(-50deg)',opacity:0},{transform:'scale(1) rotate(0deg)',opacity:1}],{delay:250,duration:500})});
}
if(q('#ns-dial')){
 const dial=q('#ns-dial'),motion=q('#ns-motion'),read=()=>Number(motion.dataset.frame);let dragging=false;
 function choose(i){q(`[data-moment="${Math.max(0,Math.min(2,i))}"]`).click()}
 function paint(){const n=read();dial.style.setProperty('--dial-angle',(n*120)+'deg');dial.style.setProperty('--arc',((n+1)*104.67)+'px');dial.setAttribute('aria-valuenow',String(n+1));dial.setAttribute('aria-valuetext',['Ankommen','Raum nehmen','Aufrichten'][n]);q('#ns-dial-value').textContent='0'+(n+1)}
 function turn(e){const r=dial.getBoundingClientRect();let angle=Math.atan2(e.clientY-r.top-r.height/2,e.clientX-r.left-r.width/2)+Math.PI/2;if(angle<0)angle+=Math.PI*2;choose(Math.round(angle/(Math.PI*2)*3)%3)}
 dial.addEventListener('pointerdown',e=>{if(e.button!==0)return;dragging=true;dial.setPointerCapture(e.pointerId);turn(e)});dial.addEventListener('pointermove',e=>{if(dragging)turn(e)});['pointerup','pointercancel','lostpointercapture'].forEach(t=>dial.addEventListener(t,()=>dragging=false));keysAt(dial,read,choose,2);watch(motion,'data-frame',()=>{paint();animate(q('#ns-moment-title'),[{opacity:0,transform:'translateY(15px)'},{opacity:1,transform:'none'}],{duration:500})});paint();
 all('[data-week]').forEach(b=>b.addEventListener('click',()=>animate(q('.ns-week-answer'),[{clipPath:'inset(0 0 100% 0)'},{clipPath:'inset(0 0 0% 0)'}],{duration:650})));
}
if(q('.ev-wall')){
 const wall=q('.ev-wall'),prints=all('.ev-print'),nav=q('.m8-exhibition-nav');let current=0,drag=null,moved=false;
 function paint(offset=0){const spatial=wall.dataset.layout==='wall';prints.forEach((p,i)=>{const d=i-current;p.style.setProperty('--ev-x',(d*wall.clientWidth*.76+offset)+'px');p.style.setProperty('--ev-scale',i===current?'1':'.76');p.style.setProperty('--ev-angle',(d*-4)+'deg');p.style.setProperty('--ev-opacity',i===current?'1':'.5');p.tabIndex=!spatial||i===current?0:-1;p.setAttribute('aria-current',String(i===current));});q('#ev-work-position').textContent='0'+(current+1)+' / '+prints[current].querySelector('b').textContent.toUpperCase();q('#ev-back').disabled=current===0;q('#ev-forward').disabled=current===2;nav.hidden=!spatial;wall.dataset.current=String(current)}
 function choose(i){current=Math.max(0,Math.min(2,i));paint()}
 q('#ev-back').addEventListener('click',()=>choose(current-1));q('#ev-forward').addEventListener('click',()=>choose(current+1));
 wall.addEventListener('click',e=>{const p=e.target.closest('.ev-print');if(!p||wall.dataset.layout!=='wall')return;const i=prints.indexOf(p);if(moved||i!==current){e.preventDefault();e.stopImmediatePropagation();if(!moved)choose(i);moved=false}},{capture:true});
 wall.addEventListener('pointerdown',e=>{if(e.button!==0||wall.dataset.layout!=='wall')return;drag={x:e.clientX,y:e.clientY};moved=false});wall.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)){moved=true;wall.setPointerCapture(e.pointerId);wall.classList.add('is-dragging');paint(dx)}});wall.addEventListener('pointerup',e=>{if(!drag)return;const dx=e.clientX-drag.x;drag=null;wall.classList.remove('is-dragging');if(moved&&Math.abs(dx)>40)choose(current+(dx<0?1:-1));else paint();setTimeout(()=>moved=false,0)});wall.addEventListener('pointercancel',()=>{drag=null;wall.classList.remove('is-dragging');paint()});wall.addEventListener('dragstart',e=>e.preventDefault());
 wall.addEventListener('keydown',e=>{if(wall.dataset.layout!=='wall')return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();choose(current+(e.key==='ArrowRight'?1:-1));prints[current].focus({preventScroll:true})}});
 all('[data-ev-layout]').forEach(b=>b.addEventListener('click',()=>{const before=prints.map(p=>p.getBoundingClientRect());queueMicrotask(()=>{paint();prints.forEach((p,i)=>{const after=p.getBoundingClientRect();if(!after.width||!before[i].width)return;animate(p,[{translate:`${before[i].left-after.left}px ${before[i].top-after.top}px`,scale:`${before[i].width/after.width}`},{translate:'0px 0px',scale:'1'}],{duration:850,delay:i*45})})})},{capture:true}));addEventListener('resize',()=>paint());paint();requestAnimationFrame(()=>requestAnimationFrame(()=>wall.classList.add('m8-ready')));
}
if(q('#sb-loupe')){
 const object=q('#sb-object'),image=q('#sb-image'),lens=q('#sb-loupe'),toggle=q('#sb-loupe-toggle');let enabled=false,position=[.5,.5];
 function paint(){if(!enabled)return;const r=object.getBoundingClientRect(),radius=lens.offsetWidth/2,ratio=image.naturalWidth/Math.max(1,image.naturalHeight),w=Math.max(r.width,r.height*ratio),h=w/ratio,x=Math.max(radius,Math.min(r.width-radius,position[0]*r.width)),y=Math.max(radius,Math.min(r.height-radius,position[1]*r.height));lens.style.left=x+'px';lens.style.top=y+'px';lens.style.backgroundImage=`url("${image.src}")`;lens.style.backgroundSize=`${w*2}px ${h*2}px`;lens.style.backgroundPosition=`${radius-(x+(w-r.width)/2)*2}px ${radius-(y+(h-r.height)/2)*2}px`}
 toggle.addEventListener('click',()=>{enabled=!enabled;lens.hidden=!enabled;q('#sb-loupe-close').hidden=!enabled;object.classList.toggle('has-loupe',enabled);toggle.setAttribute('aria-pressed',String(enabled));toggle.textContent=enabled?'Detail-Lupe schließen ⊖':'Detail-Lupe öffnen ⊕';if(enabled){q('#sb-zoom').value='100';q('#sb-zoom').dispatchEvent(new Event('input',{bubbles:true}));object.style.touchAction="none";position=[.5,.5];paint();object.focus({preventScroll:true});if(innerWidth<=900)object.scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'center'});animate(lens,[{opacity:0,scale:'.7'},{opacity:1,scale:'1'}],{duration:400})}else object.style.touchAction=Number(q('#sb-zoom').value)>100?'none':'pan-y'});
 object.addEventListener('pointerdown',e=>{if(enabled&&e.button===0&&!e.target.closest('button'))object.setPointerCapture(e.pointerId)});object.addEventListener('pointermove',e=>{if(!enabled)return;const r=object.getBoundingClientRect();position=[(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height];paint()});object.addEventListener('keydown',e=>{if(!enabled)return;const d={ArrowLeft:[-.03,0],ArrowRight:[.03,0],ArrowUp:[0,-.03],ArrowDown:[0,.03]}[e.key];if(d){e.preventDefault();position=position.map((v,i)=>Math.max(0,Math.min(1,v+d[i])));paint()}if(e.key==='Escape')toggle.click()});image.addEventListener('load',paint);addEventListener('resize',paint);watch(object,'data-view',()=>{if(enabled)object.style.touchAction='none';paint();animate(image,[{opacity:.3,clipPath:'inset(0 70% 0 0)'},{opacity:1,clipPath:'inset(0 0% 0 0)'}],{duration:850})});
 q('#sb-loupe-close').addEventListener('click',()=>toggle.click());q('#sb-zoom').addEventListener('input',()=>{if(enabled&&Number(q('#sb-zoom').value)>100)toggle.click()});q('#sb-reset').addEventListener('click',()=>{if(enabled)toggle.click()});
}
if(q('.mr-menu-card')){
 const card=q('.mr-menu-card'),buttons=all('[data-mr-menu]'),dish=q('.mr-dish'),read=()=>Number(q('[data-mr-menu][aria-pressed=true]').dataset.mrMenu),choose=i=>buttons[Math.max(0,Math.min(2,i))].click();
 swipe(card,read,choose,dx=>{if(!reduced.matches)card.style.transform=dx?`translateX(${dx*.25}px) rotate(${dx/40}deg)`:'rotate(1deg)'});keysAt(card,read,choose,2);
 buttons.forEach(b=>b.addEventListener('click',()=>animate(card,[{transform:'translateX(70px) rotate(7deg)',opacity:.15},{transform:'translateX(0px) rotate(1deg)',opacity:1}],{duration:800})));
 all('[data-dish-point]').forEach(b=>b.addEventListener('click',()=>q(`[data-mr-ingredient="${b.dataset.dishPoint}"]`).click()));
 all('[data-mr-ingredient]').forEach((b,i)=>b.addEventListener('click',()=>{all('[data-dish-point]').forEach((p,j)=>p.setAttribute('aria-pressed',String(i===j)));animate(q('#mr-ingredient-note'),[{opacity:0,transform:'translateY(10px)'},{opacity:1,transform:'none'}],{duration:500})}));
 q('[data-dish-point="0"]').setAttribute('aria-pressed','true');dish.addEventListener('pointermove',e=>{if(reduced.matches||!fine.matches)return;const r=dish.getBoundingClientRect();dish.style.setProperty('--dish-x',(-(e.clientY-r.top)/r.height*8+4)+'deg');dish.style.setProperty('--dish-y',((e.clientX-r.left)/r.width*10-5)+'deg')});dish.addEventListener('pointerleave',()=>{dish.style.setProperty('--dish-x','0deg');dish.style.setProperty('--dish-y','0deg')});
}
// Finite entrances and contextual reveals never hide the no-JS document.
animate(q('h1'),[{opacity:.15,transform:'translateY(20px)'},{opacity:1,transform:'none'}],{duration:650});
const revealTargets=all('.cw-letter h2,.cw-person figure,.jb-section h2,.lw-capabilities article,.ns-voice h2,.ev-about h2,.sb-thought>p,.mr-kitchen h2,.da-thesis h2,.al-score-lines article');
if('IntersectionObserver'in window){const seen=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){animate(e.target,[{opacity:.2,transform:'translateY(28px)'},{opacity:1,transform:'none'}],{duration:850});seen.unobserve(e.target)}}),{threshold:.18});revealTargets.forEach(e=>seen.observe(e))}
})();
