import {clamp,reflectorPresets,reflectionMaterials,reflectionPath} from './journey-models.mjs?v=7478afe2cb1d';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
export function initReflectionRoom(){
 const field=q('#reflection-field'),canvas=q('#reflection-canvas'),ctx=canvas.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)');let positions=reflectorPresets[0].map(p=>[...p]),materials=[0,1,2],selected=0,engine=null,raf=0,stopTimer=0,clockTimer=0,generation=0,dragging=-1,pulse=0;
 function score(){const colors=['#4b2a65','#875d4a','#75678b'];q('#sound-score').innerHTML='<line x1="30" y1="250" x2="570" y2="250" stroke="#3a254044"/>'+positions.map((p,i)=>{const r=reflectionPath(p,materials[i]),x=50+p[0]*470,y=240-p[1]*210;return `<path d="M30 ${90+i*55} Q${x} ${y} 570 ${90+i*55}" fill="none" stroke="${colors[i]}" stroke-width="${1+materials[i]}"/><circle cx="${x}" cy="${y}" r="5" fill="${colors[i]}"/><text x="${x+12}" y="${y+5}" fill="#3a2540" font-family="monospace" font-size="12">0${i+1} · ${Math.round(r.delay*1000)} ms</text>`}).join('')+'<text x="30" y="280" fill="#3a2540" font-family="monospace" font-size="11">DEINE ANORDNUNG / '+materials.map(i=>reflectionMaterials[i].name.toUpperCase()).join(' · ')+'</text>'}
 function paint(time=0){if(!ctx)return;const dpr=Math.min(devicePixelRatio||1,2),w=canvas.width/dpr,h=canvas.height/dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.lineWidth=1;const sx=w*.43,sy=h*.48,lx=w*.55,ly=h*.68;const active=!!engine;
  ctx.strokeStyle='#c2abda10';for(let radius=45;radius<w;radius+=50){ctx.beginPath();ctx.arc(sx,sy,radius,0,Math.PI*2);ctx.stroke()}
  positions.forEach((p,i)=>{const x=p[0]*w,y=p[1]*h,r=reflectionPath(p,materials[i]);ctx.strokeStyle=i===selected?'#efc6a8aa':'#c2abd94a';ctx.lineWidth=i===selected?1.5:1;ctx.setLineDash(materials[i]===2?[3,7]:[]);ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(x,y);ctx.lineTo(lx,ly);ctx.stroke();ctx.setLineDash([]);
   if(active&&!reduced.matches){const progress=((time/1600)+i*.29)%1;const total=Math.hypot(x-sx,y-sy)+Math.hypot(lx-x,ly-y),first=Math.hypot(x-sx,y-sy)/total;let px,py;if(progress<first){const t=progress/first;px=sx+(x-sx)*t;py=sy+(y-sy)*t}else{const t=(progress-first)/(1-first);px=x+(lx-x)*t;py=y+(ly-y)*t}ctx.fillStyle='#f0c9ae';ctx.beginPath();ctx.arc(px,py,2.5,0,Math.PI*2);ctx.fill()}
  });
 }
 function size(){const r=field.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*dpr));canvas.height=Math.max(1,Math.round(r.height*dpr));paint(performance.now())}new ResizeObserver(size).observe(field);
 function audioState(){if(!engine)return;const t=engine.context.currentTime;engine.reflections.forEach((node,i)=>{const p=reflectionPath(positions[i],materials[i]);node.delay.delayTime.setTargetAtTime(p.delay,t,.04);node.gain.gain.setTargetAtTime(p.gain,t,.06);node.filter.frequency.setTargetAtTime(p.cutoff,t,.04);node.pan.pan.setTargetAtTime(p.pan,t,.04)})}
 function controls(){qa('[data-reflector]').forEach((b,i)=>{b.style.setProperty('--x',positions[i][0]*100+'%');b.style.setProperty('--y',positions[i][1]*100+'%');b.setAttribute('aria-pressed',String(i===selected));b.dataset.material=materials[i]});q('#reflection-selected').textContent='0'+(selected+1)+' / DEINE FLÄCHE';const [x,y]=positions[selected];q('#reflection-x').value=Math.round(x*100);q('#reflection-y').value=Math.round(y*100);q('#reflection-x-value').textContent=Math.round(x*100)+' %';q('#reflection-y-value').textContent=Math.round(y*100)+' %';q('#reflection-note').textContent=reflectionMaterials[materials[selected]].copy;q('#reflection-delay').textContent=Math.round(reflectionPath(positions[selected],materials[selected]).delay*1000)+' ms';qa('[data-reflection-material]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.reflectionMaterial===materials[selected])));audioState();paint(performance.now());score()}
 const reset=()=>{positions=reflectorPresets[0].map(p=>[...p]);materials=[0,1,2];selected=0;controls()};
 qa('[data-reflector]').forEach((b,i)=>{b.addEventListener('click',()=>{selected=i;controls()});b.addEventListener('pointerdown',e=>{if(e.button!==0)return;selected=i;dragging=i;b.setPointerCapture(e.pointerId);controls()});b.addEventListener('pointermove',e=>{if(dragging!==i)return;const r=field.getBoundingClientRect();positions[i]=[clamp((e.clientX-r.left)/r.width,.14,.86),clamp((e.clientY-r.top)/r.height,.16,.81)];controls()});['pointerup','pointercancel'].forEach(type=>b.addEventListener(type,()=>dragging=-1));b.addEventListener('keydown',e=>{const m={ArrowLeft:[-.03,0],ArrowRight:[.03,0],ArrowUp:[0,-.03],ArrowDown:[0,.03]}[e.key];if(!m)return;e.preventDefault();selected=i;positions[i]=[clamp(positions[i][0]+m[0],.14,.86),clamp(positions[i][1]+m[1],.16,.81)];controls()})});
 ['x','y'].forEach((axis,i)=>q('#reflection-'+axis).addEventListener('input',e=>{positions[selected][i]=clamp(+e.target.value/100,i?.16:.14,i?.81:.86);controls()}));qa('[data-reflection-material]').forEach(b=>b.addEventListener('click',()=>{materials[selected]=+b.dataset.reflectionMaterial;controls()}));qa('[data-score]').forEach(b=>b.addEventListener('click',()=>{const i=+b.dataset.score;positions=reflectorPresets[i].map(p=>[...p]);materials=i===0?[1,2,1]:i===1?[0,0,1]:[0,1,0];controls();field.scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'center'})}));q('#sound-reset').addEventListener('click',()=>{stop();reset()});
 function stop(message='TON AUS / BEREIT'){generation++;clearTimeout(stopTimer);clearInterval(clockTimer);stopTimer=clockTimer=0;cancelAnimationFrame(raf);raf=0;const old=engine;engine=null;if(old){try{old.master.gain.cancelScheduledValues(old.context.currentTime);old.master.gain.setTargetAtTime(0,old.context.currentTime,.02)}catch{}setTimeout(()=>old.context.close().catch(()=>{}),100)}q('#sound-start').disabled=false;q('#sound-start').setAttribute('aria-pressed','false');q('#sound-start').innerHTML='Mit Klang erkunden <span>▷</span>';q('#sound-status').textContent=message;q('#sound-clock').textContent='00:30';paint()}
 function tick(t){paint(t);if(engine&&!reduced.matches)raf=requestAnimationFrame(tick)}
 async function start(){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){q('#sound-status').textContent='AUDIO NICHT VERFÜGBAR / STILLE ERKUNDUNG MÖGLICH';return}const run=++generation;let context; q('#sound-start').disabled=true;try{context=new Audio();await context.resume();if(run!==generation){context.close();return}const master=context.createGain();master.gain.value=.22;const limiter=context.createDynamicsCompressor();limiter.threshold.value=-14;limiter.ratio.value=8;master.connect(limiter);limiter.connect(context.destination);const bus=context.createGain();bus.gain.value=.24;bus.connect(master);const reflections=positions.map(()=>{const delay=context.createDelay(1),gain=context.createGain(),filter=context.createBiquadFilter(),pan=context.createStereoPanner();filter.type='lowpass';bus.connect(delay);delay.connect(filter);filter.connect(gain);gain.connect(pan);pan.connect(master);return {delay,gain,filter,pan}});
  // A composed 30-second motif: long tones, paired responses, a soft final decay.
  const notes=[174.61,261.63,349.23,220,293.66,440,261.63,349.23];const start=context.currentTime+.12;for(let n=0;n<24;n++){const t=start+n*1.1,osc=context.createOscillator(),amp=context.createGain();osc.type='sine';osc.frequency.value=notes[n%notes.length];amp.gain.value=0;amp.gain.setValueAtTime(0,t);amp.gain.linearRampToValueAtTime(n%3===0?.65:.34,t+.07);amp.gain.exponentialRampToValueAtTime(.0001,t+2.4);osc.connect(amp);amp.connect(bus);osc.start(t);osc.stop(t+2.5)}
  engine={context,master,reflections};audioState();q('#sound-start').disabled=false;q('#sound-start').setAttribute('aria-pressed','true');q('#sound-start').innerHTML='Klang anhalten <span>Ⅱ</span>';q('#sound-status').textContent='DEINE ANORDNUNG KLINGT';const deadline=performance.now()+30000;clockTimer=setInterval(()=>{q('#sound-clock').textContent='00:'+String(Math.max(0,Math.ceil((deadline-performance.now())/1000))).padStart(2,'0')},250);stopTimer=setTimeout(()=>stop('DIE KOMPOSITION IST VERKLUNGEN'),30000);if(!reduced.matches)raf=requestAnimationFrame(tick);
 }catch{if(context)context.close().catch(()=>{});if(run===generation){q('#sound-start').disabled=false;q('#sound-status').textContent='KLANG KONNTE NICHT STARTEN / BITTE ERNEUT VERSUCHEN'}}}
 q('#sound-start').addEventListener('click',()=>engine?stop():start());q('#sound-silent').addEventListener('click',()=>{stop('STILLE ERKUNDUNG');field.scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'center'});qa('[data-reflector]')[selected].focus({preventScroll:true})});
 q('#sound-export').addEventListener('click',()=>{const svg=q('#sound-score').cloneNode(true);svg.setAttribute('xmlns','http://www.w3.org/2000/svg');svg.setAttribute('width','1200');svg.setAttribute('height','600');const url=URL.createObjectURL(new Blob([svg.outerHTML],{type:'image/svg+xml'})),a=document.createElement('a');a.href=url;a.download='ada-zwischenraeume.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stop('PAUSIERT / TON AUS')});window.addEventListener('pagehide',()=>stop());new IntersectionObserver(entries=>{if(!entries[0].isIntersecting&&engine)stop('PAUSIERT / TON AUS')},{threshold:.02}).observe(q('#klangraum'));reduced.addEventListener('change',()=>{cancelAnimationFrame(raf);if(engine&&!reduced.matches)raf=requestAnimationFrame(tick);else paint()});size();controls();
}
