// One spatial model drives source positions, visual connections and audio parameters.
export const clamp=(v,min=0,max=1)=>Math.min(max,Math.max(min,v));
export function spatial(x,y){const distance=clamp(Math.hypot(x-.5,y-.53)/.65);return {pan:clamp((x-.5)*2,-1,1),distance,gain:1/(1+3*distance),cutoff:12000-10000*distance,wet:.07+.33*distance};}
export const roomPresets=[[[.25,.32],[.76,.36],[.6,.75]],[[.12,.18],[.88,.2],[.76,.82]],[[.4,.45],[.59,.42],[.55,.64]]];
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
if(typeof document!=='undefined'&&q('#al-instrument'))initRoom();
export function initRoom(){
 const reduced=matchMedia('(prefers-reduced-motion: reduce)'),field=q('#al-field'),canvas=q('#al-canvas'),draw=canvas.getContext('2d'),nodes=qa('.al-source'),play=q('#al-play'),pan=q('#al-pan'),depth=q('#al-depth'),volume=q('#al-volume');
 let positions=roomPresets[0].map(p=>[...p]),active=[true,true,true],selected=0,engine=null,raf=0,timer=null,deadline=0,generation=0,dragging=-1,frame=0;const names=['Fläche','Puls','Schimmer'];let gesture=[],recording=false,recordTimer=null,recordStart=0,replaying=false,replayRaf=0,replayStart=0;
 function paintControls(){nodes.forEach((node,i)=>{node.style.setProperty('--x',positions[i][0]*100+'%');node.style.setProperty('--y',positions[i][1]*100+'%');node.dataset.off=String(!active[i]);node.querySelector('button').setAttribute('aria-pressed',String(selected===i));});const s=spatial(...positions[selected]);pan.value=String(Math.round(s.pan*100));depth.value=String(Math.round(s.distance*100));q('#al-pan-value').textContent=Number(pan.value)>0?'+'+pan.value:pan.value;q('#al-depth-value').textContent=depth.value+' %';q('#al-volume-value').textContent=volume.value+' %';q('#al-selected').textContent=`0${selected+1} / ${names[selected]}`;q('#al-layer').textContent=active[selected]?'Quelle an':'Quelle aus';q('#al-layer').setAttribute('aria-pressed',String(active[selected]));pan.setAttribute('aria-valuetext',Math.abs(Number(pan.value))+' Prozent '+(Number(pan.value)<0?'links':'rechts'));depth.setAttribute('aria-valuetext',depth.value+' Prozent Entfernung');paintAudio();render();}
 function paintAudio(){if(!engine)return;q('#al-state').textContent='KLANG LÄUFT / '+active.filter(Boolean).length+' AKTIV';const t=engine.ctx.currentTime;engine.master.gain.setTargetAtTime(Number(volume.value)/100*.27,t,.05);engine.layers.forEach((l,i)=>{const s=spatial(...positions[i]);l.gain.gain.setTargetAtTime(active[i]?s.gain*.19:0,t,.06);l.pan.pan.setTargetAtTime(s.pan,t,.06);l.filter.frequency.setTargetAtTime(s.cutoff,t,.08);l.wet.gain.setTargetAtTime(s.wet,t,.08);});}
 function render(){if(!draw)return;const w=canvas.width,h=canvas.height;draw.clearRect(0,0,w,h);const cx=w*.5,cy=h*.53;let amplitudes=[0,0,0];if(engine){engine.layers.forEach((l,i)=>{const a=new Float32Array(128);l.analyser.getFloatTimeDomainData(a);amplitudes[i]=Math.sqrt(a.reduce((s,n)=>s+n*n,0)/a.length)})}if(gesture.length>1){for(let i=0;i<3;i++){draw.beginPath();gesture.forEach((sample,j)=>{const [x,y]=sample.p[i];if(j===0)draw.moveTo(x*w,y*h);else draw.lineTo(x*w,y*h)});draw.strokeStyle=['#f2b58688','#a6c7d077','#d3bded77'][i];draw.lineWidth=1.5;draw.stroke()}}positions.forEach(([x,y],i)=>{const px=x*w,py=y*h;draw.strokeStyle=active[i]?'#a6c7d04d':'#a6c7d01f';draw.lineWidth=1;draw.setLineDash(active[i]?[]:[4,7]);draw.beginPath();draw.moveTo(px,py);draw.lineTo(cx,cy);draw.stroke();draw.setLineDash([]);if(!engine||!active[i]||reduced.matches)return;const radius=22+Math.min(60,amplitudes[i]*240);draw.strokeStyle=i===selected?'#f2b586':'#a6c7d0';draw.globalAlpha=.55;draw.beginPath();draw.ellipse(px,py,radius,radius,0,0,Math.PI*2);draw.stroke();const progress=(frame/110+i*.31)%1;draw.globalAlpha=.28*(1-progress);draw.beginPath();draw.ellipse(px+(cx-px)*progress,py+(cy-py)*progress,3,3,0,0,Math.PI*2);draw.fillStyle='#f2b586';draw.fill();draw.globalAlpha=1;});}
 function animate(){raf=0;frame++;render();if(engine&&!reduced.matches)raf=requestAnimationFrame(animate)}
 function size(){const r=field.getBoundingClientRect(),scale=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*scale));canvas.height=Math.max(1,Math.round(r.height*scale));render();}new ResizeObserver(size).observe(field);
 function select(i){selected=i;paintControls()}
 function clearPreset(){qa('[data-room-preset]').forEach(b=>b.setAttribute('aria-pressed','false'))}
 function position(e){const r=field.getBoundingClientRect();positions[dragging]=[clamp((e.clientX-r.left)/r.width,.1,.9),clamp((e.clientY-r.top)/r.height,.15,.82)];clearPreset();paintControls()}
 nodes.forEach((node,i)=>{const button=node.querySelector('button');button.addEventListener('click',()=>select(i));button.addEventListener('pointerdown',e=>{if(e.button!==0)return;stopReplay();dragging=i;selected=i;button.setPointerCapture(e.pointerId);paintControls()});button.addEventListener('pointermove',e=>{if(dragging===i)position(e)});button.addEventListener('pointerup',()=>dragging=-1);button.addEventListener('pointercancel',()=>dragging=-1);button.addEventListener('keydown',e=>{const move={ArrowLeft:[-.03,0],ArrowRight:[.03,0],ArrowUp:[0,-.03],ArrowDown:[0,.03]}[e.key];if(!move)return;e.preventDefault();stopReplay();selected=i;positions[i]=[clamp(positions[i][0]+move[0],.1,.9),clamp(positions[i][1]+move[1],.15,.82)];clearPreset();paintControls()})});
 pan.addEventListener('input',()=>{stopReplay();positions[selected][0]=clamp(.5+Number(pan.value)/200,.1,.9);clearPreset();paintControls()});
 depth.addEventListener('input',()=>{stopReplay();const [x,y]=positions[selected],theta=Math.atan2(y-.53,x-.5),r=Number(depth.value)/100*.65;positions[selected]=[clamp(.5+Math.cos(theta)*r,.1,.9),clamp(.53+Math.sin(theta)*r,.15,.82)];clearPreset();paintControls()});
 volume.addEventListener('input',paintControls);q('#al-layer').addEventListener('click',()=>{active[selected]=!active[selected];paintControls()});
 qa('[data-room-preset]').forEach(b=>b.addEventListener('click',()=>{stopReplay();positions=roomPresets[Number(b.dataset.roomPreset)].map(p=>[...p]);qa('[data-room-preset]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));paintControls()}));
 function gestureState(text){if(q('#al-gesture-state'))q('#al-gesture-state').textContent=text}
 function stopReplay(){if(!replaying)return;replaying=false;cancelAnimationFrame(replayRaf);replayRaf=0;field.classList.remove('is-replaying');q('#al-replay')?.setAttribute('aria-pressed','false');if(q('#al-replay'))q('#al-replay').textContent='Spur abspielen';gestureState('Die Spur bleibt im Raum. Du kannst sie erneut abspielen.')}
 function capturePose(){const t=Math.min(8000,performance.now()-recordStart);gesture.push({t,p:positions.map(p=>[...p])});q('.m8-gesture')?.style.setProperty('--gesture',t/80+'%');gestureState('AUFNAHME / '+(t/1000).toFixed(1).replace('.',',')+' von 8 Sekunden');if(t>=8000)finishRecording()}
 function finishRecording(){if(!recording)return;recording=false;clearInterval(recordTimer);recordTimer=null;q('#al-record').setAttribute('aria-pressed','false');q('#al-record').textContent='Neue Bewegung aufnehmen';const ready=gesture.length>2&&gesture.at(-1).t>150;q('#al-replay').disabled=!ready;gestureState(ready?'Deine Bewegung ist aufgezeichnet. Spiele die Spur ab.':'Bewege eine Quelle etwas länger, um eine Spur aufzunehmen.');render()}
 if(q('#al-record')){
 q('#al-record').addEventListener('click',()=>{if(recording){capturePose();finishRecording();return}stopReplay();gesture=[];recording=true;recordStart=performance.now();q('#al-record').setAttribute('aria-pressed','true');q('#al-record').textContent='Aufnahme beenden';q('#al-replay').disabled=true;capturePose();recordTimer=setInterval(capturePose,50)});
 q('#al-replay').addEventListener('click',()=>{if(replaying){stopReplay();return}if(gesture.length<3)return;finishRecording();replaying=true;replayStart=performance.now();field.classList.add('is-replaying');q('#al-replay').setAttribute('aria-pressed','true');q('#al-replay').textContent='Spur anhalten';gestureState('DEINE SPUR / Bewegt sich mit dem Klang, wenn er läuft.');let index=0;const duration=gesture.at(-1).t;
 const follow=()=>{if(!replaying)return;const t=Math.min(duration,performance.now()-replayStart);while(index<gesture.length-2&&gesture[index+1].t<t)index++;const a=gesture[index],b=gesture[Math.min(index+1,gesture.length-1)],mix=b.t===a.t?1:clamp((t-a.t)/(b.t-a.t));positions=a.p.map((p,i)=>p.map((v,j)=>v+(b.p[i][j]-v)*mix));paintControls();q('.m8-gesture').style.setProperty('--gesture',t/duration*100+'%');if(t>=duration){stopReplay();return}replayRaf=requestAnimationFrame(follow)};follow()});
 q('#al-reset').addEventListener('click',()=>{finishRecording();stopReplay();gesture=[];q('#al-replay').disabled=true;q('.m8-gesture').style.setProperty('--gesture','0%');gestureState('Zeichne mit den Quellen eine eigene Bewegung. Bis zu 8 Sekunden.');render()});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){finishRecording();stopReplay()}});window.addEventListener('pagehide',()=>{finishRecording();stopReplay()});new IntersectionObserver(entries=>{if(!entries[0].isIntersecting){finishRecording();stopReplay()}},{threshold:.02}).observe(q('#al-instrument'));reduced.addEventListener('change',()=>{finishRecording();stopReplay()});
 }
 function stop(message='BEREIT / TON AUS'){generation++;clearInterval(timer);timer=null;cancelAnimationFrame(raf);raf=0;const old=engine;engine=null;if(old){old.master.gain.cancelScheduledValues(old.ctx.currentTime);old.master.gain.setTargetAtTime(0,old.ctx.currentTime,.015);setTimeout(()=>{old.oscillators.forEach(o=>{try{o.stop()}catch{}});old.ctx.close().catch(()=>{})},80)}play.disabled=false;play.setAttribute('aria-pressed','false');play.innerHTML='Klangraum starten <span>▷</span>';q('#al-state').textContent=message;q('#al-clock').textContent='00:30';render()}
 async function start(){const AudioEngine=window.AudioContext||window.webkitAudioContext;const error=q('#al-audio-error');error.hidden=true;if(!AudioEngine){error.hidden=false;error.textContent='Audio ist in diesem Browser nicht verfügbar. Die Raumskizze lässt sich weiterhin erkunden.';return}let ctx;const run=++generation;play.disabled=true;try{ctx=new AudioEngine();await ctx.resume();if(run!==generation){await ctx.close();return}const master=ctx.createGain();master.gain.value=0;master.connect(ctx.destination);const layers=[],oscillators=[];[[174.61,175.14],[130.81],[523.25,783.99]].forEach((frequencies,i)=>{const gain=ctx.createGain(),panner=ctx.createStereoPanner(),filter=ctx.createBiquadFilter(),analyser=ctx.createAnalyser(),delay=ctx.createDelay(1),wet=ctx.createGain();gain.gain.value=0;filter.type='lowpass';filter.frequency.value=9000;analyser.fftSize=256;delay.delayTime.value=.19+i*.11;wet.gain.value=.1;filter.connect(gain);gain.connect(panner);panner.connect(analyser);analyser.connect(master);panner.connect(delay);delay.connect(wet);wet.connect(master);frequencies.forEach(frequency=>{const osc=ctx.createOscillator(),tone=ctx.createGain();osc.type=i===1?'triangle':'sine';osc.frequency.value=frequency;tone.gain.value=1/frequencies.length;osc.connect(tone);tone.connect(filter);if(i>0){const lfo=ctx.createOscillator(),amplitude=ctx.createGain();tone.gain.value=.42;lfo.frequency.value=i===1?.7:.17;amplitude.gain.value=.32;lfo.connect(amplitude);amplitude.connect(tone.gain);lfo.start();oscillators.push(lfo)}osc.start();oscillators.push(osc)});layers.push({gain,pan:panner,filter,wet,analyser})});engine={ctx,master,layers,oscillators};deadline=performance.now()+30000;play.disabled=false;play.setAttribute('aria-pressed','true');play.innerHTML='Klangraum stoppen <span>Ⅱ</span>';q('#al-state').textContent='KLANG LÄUFT';paintAudio();timer=setInterval(()=>{const left=Math.ceil((deadline-performance.now())/1000);q('#al-clock').textContent='00:'+String(Math.max(0,left)).padStart(2,'0');if(left<=0)stop('DIE SKIZZE IST VERKLANGEN')},250);animate()}catch{if(ctx&&ctx.state!=='closed')ctx.close().catch(()=>{});if(run===generation){engine=null;play.disabled=false;play.setAttribute('aria-pressed','false');error.hidden=false;error.textContent='Der Klang konnte nicht starten. Bitte erneut versuchen oder die Skizze ohne Ton erkunden.';q('#al-state').textContent='TON AUS / START NICHT MÖGLICH'}}}
 play.addEventListener('click',()=>engine?stop():start());
 qa('[data-solo]').forEach(b=>b.addEventListener('click',()=>{stop();selected=Number(b.dataset.solo);active=active.map((_,i)=>i===selected);paintControls();q('#hoeren').scrollIntoView({behavior:reduced.matches?'instant':'smooth'});}));
 q('#al-reset').addEventListener('click',()=>{stop();positions=roomPresets[0].map(p=>[...p]);active=[true,true,true];selected=0;volume.value='35';qa('[data-room-preset]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===0)));paintControls()});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stop('PAUSIERT / TON AUS')});window.addEventListener('pagehide',()=>stop());new IntersectionObserver(entries=>{if(!entries[0].isIntersecting&&(engine||play.disabled))stop('PAUSIERT / TON AUS')},{threshold:.02}).observe(q('#al-instrument'));reduced.addEventListener('change',()=>{cancelAnimationFrame(raf);raf=0;if(engine&&!reduced.matches)animate();else render()});size();paintControls();
}
