(()=>{'use strict';
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const contact=document.querySelector('#contact-dialog');document.querySelectorAll('[data-contact]').forEach(b=>b.addEventListener('click',()=>contact.showModal()));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));contact?.addEventListener('click',e=>{const r=contact.getBoundingClientRect();if(e.target===contact&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))contact.close()});
const zoom=document.querySelector('#object-zoom');if(zoom){const target=document.querySelector('#j-object-image'),output=document.querySelector('#zoom-value');function update(){const value=Number(zoom.value)/100;target.style.setProperty('--detail-scale',String(value));output.textContent=value.toFixed(1).replace('.',',')+'×';zoom.setAttribute('aria-valuetext',output.textContent)}zoom.addEventListener('input',update);document.querySelector('#zoom-reset').addEventListener('click',()=>{zoom.value='100';update()});update()}
const menuButtons=[...document.querySelectorAll('[data-menu]')];if(menuButtons.length){const menus=[{title:'Die Pflanze im Mittelpunkt.',courses:[['Tomate · Pfirsich · Basilikum','Fruchtig, frisch und voller Sommer.'],['Aubergine · Bohne · Zitrone','Geröstete Aromen, eine weiche Mitte.'],['Aprikose · Mandel · Rosmarin','Ein warmer Abschluss mit feiner Säure.']]},{title:'Ein Gruß vom Wasser.',courses:[['Gurke · Dill · Buttermilch','Ein kühler Auftakt mit frischen Kräutern.'],['Saibling · Fenchel · Kartoffel','Sanfte Aromen und eine klare Richtung.'],['Erdbeere · Joghurt · Verbene','Frucht und Frische für den letzten Gang.']]},{title:'Was der Garten erzählt.',courses:[['Rote Bete · Frischkäse · Kräuteröl','Erdige Süße und ein heller Gegenpol.'],['Ravioli · Erbse · Salbei','Ein wenig Handarbeit, viel grüner Geschmack.'],['Birne · Haselnuss · Vanille','Vertraute Aromen in einer neuen Begegnung.']]}];const labels=['ZUM ANKOMMEN','MITTEN IM ABEND','NOCH EIN MOMENT'];function choose(i){menuButtons.forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)));document.querySelector('#menu-title').textContent=menus[i].title;const list=document.querySelector('#menu-courses');list.replaceChildren();menus[i].courses.forEach((course,j)=>{const li=document.createElement('li'),tag=document.createElement('span'),name=document.createElement('strong'),copy=document.createElement('p');tag.textContent=labels[j];name.textContent=course[0];copy.textContent=course[1];li.append(tag,name,copy);list.append(li)})}menuButtons.forEach((b,i)=>b.addEventListener('click',()=>choose(i)));document.querySelector('.c-menu-choices').addEventListener('keydown',e=>{const i=menuButtons.indexOf(document.activeElement);if(i<0)return;let n=i;if(e.key==='ArrowDown'||e.key==='ArrowRight')n=(i+1)%3;else if(e.key==='ArrowUp'||e.key==='ArrowLeft')n=(i+2)%3;else return;e.preventDefault();menuButtons[n].focus();choose(n)})}
const play=document.querySelector('#sound-start');if(!play)return;
const status=document.querySelector('#sound-state'),label=document.querySelector('#sound-button-label'),instrument=document.querySelector('.s-instrument'),layers=[...document.querySelectorAll('[data-layer]')],space=document.querySelector('#sound-space'),canvas=document.querySelector('#sound-wave'),graphic=canvas.getContext('2d');let selected=[true,false,false],engine=null,ending=null,raf=0,generation=0;const levels=[.22,.18,.09];
function draw(){if(!graphic)return;const width=canvas.width,height=canvas.height;graphic.clearRect(0,0,width,height);graphic.lineWidth=1.5;graphic.strokeStyle='#e4f15d';graphic.beginPath();if(engine&&!reduced.matches){const buffer=new Float32Array(engine.analyser.fftSize);engine.analyser.getFloatTimeDomainData(buffer);for(let i=0;i<buffer.length;i++){const x=i*width/(buffer.length-1),y=height/2+buffer[i]*height*3.1;i?graphic.lineTo(x,y):graphic.moveTo(x,y)}}else{graphic.moveTo(0,height/2);graphic.lineTo(width,height/2)}graphic.stroke();}
function animate(){raf=0;draw();if(engine&&!reduced.matches)raf=requestAnimationFrame(animate)}
function paintControls(){layers.forEach((b,i)=>b.setAttribute('aria-pressed',String(selected[i])));if(engine){const now=engine.ctx.currentTime;engine.layerGains.forEach((g,i)=>g.gain.setTargetAtTime(selected[i]?levels[i]:0,now,.07));status.textContent=selected.some(Boolean)?'KLANG LÄUFT':'ALLE EBENEN AUS'}}
function setSpace(){space.setAttribute('aria-valuetext',space.value+' Prozent Raumtiefe');if(!engine)return;const v=Number(space.value)/100;engine.delay.delayTime.setTargetAtTime(.06+v*.34,engine.ctx.currentTime,.1);engine.wet.gain.setTargetAtTime(v*.32,engine.ctx.currentTime,.1)}
function stop(message='TON AUS'){generation++;clearTimeout(ending);ending=null;cancelAnimationFrame(raf);raf=0;const old=engine;engine=null;if(old){old.master.gain.cancelScheduledValues(old.ctx.currentTime);old.master.gain.setTargetAtTime(0,old.ctx.currentTime,.015);setTimeout(()=>{old.oscillators.forEach(o=>{try{o.stop()}catch{}});old.ctx.close().catch(()=>{})},60)}play.disabled=false;play.setAttribute('aria-pressed','false');label.textContent='Klang starten';play.lastElementChild.textContent='▷';status.textContent=message;instrument.classList.remove('is-playing');draw()}
async function start(){const AudioEngine=window.AudioContext||window.webkitAudioContext;if(!AudioEngine){status.textContent='AUDIO HIER NICHT VERFÜGBAR';return}const run=++generation;play.disabled=true;status.textContent='KLANG WIRD VORBEREITET';let ctx;try{ctx=new AudioEngine();await ctx.resume();if(run!==generation){await ctx.close();return}const master=ctx.createGain(),analyser=ctx.createAnalyser(),delay=ctx.createDelay(1),wet=ctx.createGain();master.gain.value=.18;analyser.fftSize=1024;wet.gain.value=0;delay.delayTime.value=.16;master.connect(analyser);analyser.connect(ctx.destination);const dry=ctx.createGain();dry.connect(master);dry.connect(delay);delay.connect(wet);wet.connect(master);const layerGains=[],oscillators=[];[174.61,196,523.25].forEach((frequency,i)=>{const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.type=i===1?'triangle':'sine';oscillator.frequency.value=frequency;gain.gain.value=0;if(i===1){const tremolo=ctx.createGain(),lfo=ctx.createOscillator(),depth=ctx.createGain();tremolo.gain.value=.5;lfo.frequency.value=.8;depth.gain.value=.45;lfo.connect(depth);depth.connect(tremolo.gain);oscillator.connect(tremolo);tremolo.connect(gain);lfo.start();oscillators.push(lfo)}else oscillator.connect(gain);gain.connect(dry);oscillator.start();layerGains.push(gain);oscillators.push(oscillator)});engine={ctx,master,analyser,delay,wet,layerGains,oscillators};paintControls();setSpace();play.setAttribute('aria-pressed','true');label.textContent='Klang stoppen';play.lastElementChild.textContent='Ⅱ';instrument.classList.add('is-playing');ending=setTimeout(()=>stop('SKIZZE BEENDET / 30 SEKUNDEN'),30000);animate()}catch{if(ctx&&ctx.state!=='closed')ctx.close().catch(()=>{});if(run===generation){engine=null;status.textContent='KLANG KONNTE NICHT STARTEN';play.setAttribute('aria-pressed','false');instrument.classList.remove('is-playing')}}finally{if(run===generation)play.disabled=false}}
play.addEventListener('click',()=>engine?stop():start());layers.forEach((b,i)=>b.addEventListener('click',()=>{selected[i]=!selected[i];paintControls()}));space.addEventListener('input',setSpace);document.addEventListener('visibilitychange',()=>{if(document.hidden){if(engine||play.disabled)stop('PAUSIERT / TON AUS')}});window.addEventListener('pagehide',()=>stop());reduced.addEventListener('change',()=>{cancelAnimationFrame(raf);raf=0;animate()});paintControls();setSpace();draw();
})();
