#!/usr/bin/env bash
# Sprint 18b — Alle 79 Bilder mit GPT-Image-1 (OpenAI)
# Persona-DNA pro Branche → Wiedererkennbarkeit über Hero+Galerie

set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
[ -f "$REPO_ROOT/.env.local" ] && { set -a; . "$REPO_ROOT/.env.local"; set +a; }
[ -z "${OPENAI_API_KEY:-}" ] && { echo "FEHLER: OPENAI_API_KEY nicht gesetzt."; exit 1; }
OUT_DIR="$REPO_ROOT/src/images"
ENDPOINT="https://api.openai.com/v1/images/generations"
MODEL="gpt-image-1"

# Format: key|path|size|quality|prompt
# size: 1024x1024 (1:1), 1024x1536 (2:3 portrait), 1536x1024 (3:2 landscape)
# quality: high (premium), medium (galleries)

read -r -d '' ITEMS_RAW <<'EOF' || true
hero-immobilien|immobilien-stadtmakler-mockup.jpg|1536x1024|high|Editorial premium real estate website mockup hero composition. Subject: a distinguished German real estate executive named Andreas Mueller in his early fifties with short salt-and-pepper hair, wearing a tailored navy blazer over a crisp white shirt, confident composed expression. Setting: standing relaxed in front of an upscale Stuttgart Halbhoehenring sandstone Altbau building entrance with ornate stucco facade and dark wooden door. Lighting: soft golden afternoon side light. Composition: rule of thirds, persona on the right third, editorial empty space on the left third for headline overlay, blurred upscale tree-lined residential street in deep background, shallow depth of field. Color palette: navy and warm gold tones. Style: high-end real estate magazine editorial photography. Constraints: absolutely no text, no logos, no readable signs, no captions, no watermarks, photorealistic, sharp focus on the persona, natural skin texture.
hero-friseur|friseur-mueller-mockup.jpg|1536x1024|high|Editorial premium hair salon website mockup hero composition. Subject: a confident German hair salon owner named Laura Mueller in her mid-forties with shoulder-length warm brown hair, wearing an elegant dark apron over a white blouse, calm relaxed expression. Setting: blurred Aveda concept salon interior with marble countertops, brass mirror details, warm wooden accents and pendant lighting. Lighting: soft window light from the right, vogue-inspired warm tone. Composition: rule of thirds, persona on the right third, editorial empty space on the left third, blurred salon depth. Color palette: aubergine, dusty rose, brass accents. Style: vogue beauty magazine editorial photography. Constraints: absolutely no text, no logos, no readable signs, photorealistic, sharp focus on the persona, natural skin texture, hair details crisp.
hero-dachdecker|dachdecker-meister-mockup.jpg|1536x1024|high|Documentary premium German craftsman website mockup hero composition. Subject: a weathered authentic German roofing master named Thomas Berger in his early fifties with short gray hair and a neatly trimmed gray beard, wearing a clean dark navy work shirt rolled up at the sleeves, grounded confident expression. Setting: standing on a Stuttgart residential rooftop with newly-laid terracotta tiles. Lighting: soft overcast natural daylight. Composition: rule of thirds, persona on the right third, blurred Stuttgart skyline silhouette in the deep background, editorial empty space on the left for headline overlay. Color palette: deep blacks, warm terracotta, hints of gold. Style: premium documentary craftsman magazine photography. Constraints: absolutely no text, no logos, no readable signs, no brand patches, photorealistic, sharp focus on the persona, natural weathered skin texture.
hero-praxis|praxis-weber-mockup.jpg|1536x1024|high|Editorial modern medical practice website mockup hero composition. Subject: a warm friendly German female general practitioner named Dr. Sarah Weber in her mid-forties with brown hair tied back, wearing a pristine white doctor coat over a light pastel blouse, authentic warm smile. Setting: blurred modern Munich medical practice interior with subtle teal accents, natural plants, large windows. Lighting: warm natural daylight from a large window. Composition: rule of thirds, persona on the right third, editorial empty space on the left third, blurred medical interior. Color palette: clean blue, soft teal, warm neutrals. Style: premium healthcare editorial magazine photography. Constraints: absolutely no text, no logos, no readable signs, no stethoscope visible, photorealistic, sharp focus on the persona, natural skin texture.
hero-gastro|gastro-hirsch-mockup.jpg|1536x1024|high|Editorial premium gastronomy magazine website mockup hero composition. Subject: a distinguished German executive chef named Andreas Bauer in his early fifties with neat salt-and-pepper hair, wearing a classic white double-breasted chef jacket with cloth knot buttons buttoned to the top, focused calm expression. Setting: blurred fine dining restaurant kitchen background with stainless steel surfaces and warm copper pendant lights. Lighting: warm tungsten side light from the left. Composition: rule of thirds, persona on the right third, holding a wooden cutting board casually in one hand, editorial empty space on the left third, blurred kitchen depth. Color palette: espresso brown, warm copper, off-white. Style: premium gastronomy magazine editorial photography. Constraints: absolutely no text, no logos, no readable signs on the jacket, photorealistic, sharp focus on the persona, natural skin texture.
hero-handwerk|handwerk-mueller-mockup.jpg|1536x1024|high|Documentary trustworthy German craftsman website mockup hero composition. Subject: a trustworthy German sanitary master craftsman named Stefan Mueller in his mid-forties with short brown hair, wearing a completely plain dark blue work polo shirt without any logo or patch or brand mark, confident hands-on expression. Setting: blurred modern bathroom showroom with white ceramic basins, chrome fixtures and visible copper pipes. Lighting: natural cool daylight. Composition: rule of thirds, persona on the right third, holding a chrome pipe wrench casually, editorial empty space on the left third. Color palette: petrol blue, chrome, copper highlights. Style: premium documentary handwerker editorial photography. Constraints: absolutely no text, no logos, no readable signs, completely plain shirt no patches no brand, photorealistic, sharp focus on the persona, natural skin texture.
hero-logistik|logistik-schwaben-mockup.jpg|1536x1024|high|Editorial B2B premium logistics company website mockup hero composition. Subject: NO PEOPLE VISIBLE. Setting: a fleet of modern Mercedes-Benz Actros white semi-trucks neatly parked on a clean Filderstadt logistics yard. Lighting: warm dawn sunrise golden hour light. Composition: rule of thirds, fleet on the right two-thirds in three-quarter view, blurred German autobahn silhouette in deep background, editorial empty space on the left third for headline overlay. Color palette: slate gray, dawn orange, white. Style: premium German Mittelstand corporate editorial photography. Constraints: absolutely no text, no logos, no readable license plates, no readable signs on trucks, photorealistic, sharp focus on the fleet, no people visible.
hero-coaching|coaching-lehmann-mockup.jpg|1536x1024|high|Editorial business coaching website mockup hero composition. Subject: a confident German female business coach named Sarah Lehmann in her mid-forties with dark hair in a sleek bob, wearing a minimalist black blazer over a white shell, composed authoritative warm expression. Setting: sitting at a glass conference table with subtle blurred Frankfurt skyline view through floor-to-ceiling windows. Lighting: warm afternoon side light from the windows. Composition: rule of thirds, persona on the right third, editorial empty space on the left third, blurred upscale office background. Color palette: monochrome blacks and whites with subtle warm window glow. Style: premium business magazine editorial photography. Constraints: absolutely no text, no logos, no readable signs, photorealistic, sharp focus on the persona, natural skin texture.
persona-immobilien|immobilien/andreas-team.jpg|1024x1536|high|Editorial premium portrait photograph. Subject: a distinguished German real estate executive named Andreas Mueller in his early fifties with short salt-and-pepper hair, well-groomed clean-shaven, wearing a tailored navy blazer over a crisp white shirt, no tie, confident composed expression looking directly at the camera. Setting: standing in front of an upscale Stuttgart Halbhoehenring sandstone Altbau building exterior with ornate stucco. Lighting: soft golden afternoon side light from camera left. Composition: medium portrait, head and torso visible, slight three-quarter body angle, shallow depth of field with blurred building behind. Color palette: navy and warm gold tones. Style: editorial real estate magazine portrait, photorealistic. Constraints: absolutely no text, no logos, no readable signs, no watermarks, natural skin texture with subtle character.
persona-friseur|friseur/persona.jpg|1024x1536|high|Editorial premium portrait photograph. Subject: a confident German hair salon owner named Laura Mueller in her mid-forties with shoulder-length warm brown hair, subtle natural makeup, wearing an elegant dark forest-green apron over a crisp white blouse, calm relaxed slight smile looking directly at the camera. Setting: blurred Aveda concept salon interior with marble countertop and brass mirror details. Lighting: soft window light from camera right, vogue-inspired warm tone. Composition: medium portrait, head and torso visible, slight three-quarter angle, shallow depth of field. Color palette: aubergine, dusty rose, brass accents. Style: vogue beauty magazine portrait, photorealistic. Constraints: absolutely no text, no logos, no readable signs, hair details crisp, natural skin texture.
persona-dachdecker|dachdecker/persona.jpg|1024x1536|high|Documentary premium portrait photograph. Subject: a weathered authentic German roofing master named Thomas Berger in his early fifties with short gray hair and a neatly trimmed gray beard, wearing a clean dark navy work shirt with sleeves rolled up showing forearms, grounded confident expression looking directly at the camera with a faint smile. Setting: blurred Stuttgart rooftop with newly-laid terracotta tiles. Lighting: soft overcast natural daylight. Composition: medium portrait, head and torso visible, three-quarter body angle. Color palette: deep blacks, warm terracotta, hints of gold. Style: documentary craftsman magazine portrait, photorealistic. Constraints: absolutely no text, no logos, no readable signs, no brand patches, natural weathered skin texture with character.
persona-praxis|praxis/persona.jpg|1024x1536|high|Editorial premium portrait photograph. Subject: a warm friendly German female general practitioner named Dr. Sarah Weber in her mid-forties with brown hair tied back in a low practical knot, subtle natural makeup, wearing a pristine white doctor coat over a soft pastel blouse, authentic warm smile looking directly at the camera. Setting: blurred modern Munich medical practice interior with subtle teal accents and natural plants. Lighting: warm natural daylight from a window camera left. Composition: medium portrait, head and torso visible, slight three-quarter angle. Color palette: clean blue, soft teal, warm neutrals. Style: premium healthcare editorial portrait, photorealistic. Constraints: absolutely no text, no logos, no readable signs, no stethoscope visible, natural skin texture.
persona-restaurant|restaurant/persona.jpg|1024x1536|high|Editorial premium portrait photograph. Subject: a distinguished German executive chef named Andreas Bauer in his early fifties with neat salt-and-pepper hair, well-groomed, wearing a classic white double-breasted chef jacket with cloth knot buttons buttoned to the top, focused calm expression with a faint warm smile looking directly at the camera. Setting: blurred fine dining restaurant kitchen background with stainless steel surfaces and warm copper pendant lights. Lighting: warm tungsten side light from camera left. Composition: medium portrait, head and torso visible, holding a wooden cutting board low in one hand, three-quarter body angle. Color palette: espresso brown, warm copper, off-white. Style: gastronomy magazine portrait, photorealistic. Constraints: absolutely no text, no logos, no readable signs, no brand patches on jacket, natural skin texture.
persona-sanitaer|sanitaer/persona.jpg|1024x1536|high|Documentary premium portrait photograph. Subject: a trustworthy German sanitary master craftsman named Stefan Mueller in his mid-forties with short brown hair, clean-shaven, wearing a completely plain dark blue work polo shirt without any logo or patch or brand mark, confident hands-on expression with a faint smile looking directly at the camera. Setting: blurred modern bathroom showroom with white ceramic basins, chrome fixtures and copper pipes. Lighting: natural cool daylight from camera right. Composition: medium portrait, head and torso visible, holding a chrome pipe wrench low in one hand, three-quarter body angle. Color palette: petrol blue, chrome, copper highlights. Style: documentary craftsman magazine portrait, photorealistic. Constraints: absolutely no text, no logos, no readable signs, completely plain shirt no patches no brand, natural skin texture.
immo-altbau|immobilien/altbau-west.jpg|1536x1024|medium|Editorial premium real estate exterior photograph of an upscale Stuttgart Halbhoehenring sandstone Altbau apartment building from the late 19th century. Architecture: ornate facade with stucco details, tall French windows with wrought iron balconies, a dark wooden double door. Setting: tree-lined upscale residential street in Stuttgart-West. Lighting: golden hour afternoon side light casting warm shadows. Composition: three-quarter view of the facade, full height visible, rule of thirds. Style: high-end real estate magazine architectural photography. Constraints: absolutely no text, no logos, no readable signs, no license plates, no people visible.
immo-efh|immobilien/efh-degerloch.jpg|1536x1024|medium|Editorial premium real estate exterior photograph of a 1960s modernist single-family home in Stuttgart-Degerloch. Architecture: clean architectural lines with large picture windows, flat roof, natural stone accents, wide carport. Setting: mature landscaped garden with manicured hedges and a beech tree, paved entry path. Lighting: soft warm afternoon natural light. Composition: three-quarter view of the house, rule of thirds. Style: premium real estate magazine architectural photography. Constraints: absolutely no text, no logos, no readable signs, no license plates, no people visible.
immo-penthouse|immobilien/penthouse-mitte.jpg|1536x1024|medium|Editorial premium real estate interior photograph of a Stuttgart penthouse living room. Architecture: floor-to-ceiling windows with views of the Stuttgart city skyline, polished concrete or light oak flooring, double-height ceiling. Furniture: modern minimalist Vitra-style seating arrangement in warm neutral tones, single sculptural pendant lamp, large neutral abstract art on one wall. Lighting: dusk natural light through windows with subtle warm interior accent lights, Stuttgart skyline lights visible. Composition: wide interior shot, rule of thirds, depth into the skyline view. Style: premium real estate magazine interior photography. Constraints: absolutely no text, no logos, no readable signs, no people visible.
immo-poster1|immobilien/video-poster-1.jpg|1536x1024|medium|Editorial documentary portrait photograph. Subject: a friendly German woman seller named Ute in her mid-sixties with short well-styled gray hair, wearing a soft beige cardigan over a cream blouse, warm trustworthy expression looking at camera. Setting: sitting relaxed in her bright Stuttgart-West Altbau living room with warm afternoon light from a side window. Lighting: warm window light from camera right. Composition: three-quarter portrait, head and shoulders, blurred bookshelves and houseplants in background, depth of field. Style: premium documentary portrait. Constraints: absolutely no text, no logos, natural skin texture with age character.
immo-poster2|immobilien/video-poster-2.jpg|1536x1024|medium|Editorial documentary portrait photograph. Subject: a composed German woman seller named Sigrid in her late sixties with shoulder-length silver-gray hair pinned back, wearing a navy blouse with a subtle silver brooch, reserved dignified expression looking at camera. Setting: sitting in her Degerloch family home garden patio at golden hour, blurred mature garden background with roses. Lighting: warm golden hour side light. Composition: three-quarter portrait, head and shoulders. Style: premium documentary portrait. Constraints: absolutely no text, no logos, natural skin texture with age character.
immo-poster3|immobilien/video-poster-3.jpg|1536x1024|medium|Editorial documentary portrait photograph. Subject: a thoughtful German man named Markus in his mid-fifties with neat short brown hair lightly graying at the temples, clean-shaven, wearing a dark gray crewneck sweater over a white shirt, calm reflective expression looking at camera. Setting: sitting at a wooden kitchen table in an inherited Stuttgart family home with vintage details. Lighting: warm side window light. Composition: three-quarter portrait, head and shoulders, blurred family-home interior. Style: premium documentary portrait. Constraints: absolutely no text, no logos, natural skin texture.
fr-salon-empfang|friseur/salon-empfang.jpg|1536x1024|medium|Editorial premium hair salon reception area photograph. Subject: NO PEOPLE. Setting: an Aveda concept salon in Duesseldorf with a marble-topped reception desk featuring brass details, a curated display of sustainable Aveda-style hair care products, warm wooden accents. Lighting: soft warm pendant lighting overhead. Composition: rule of thirds, reception desk on the right two-thirds, blurred salon interior extending into the background. Color palette: aubergine, dusty rose, brass. Style: vogue beauty magazine architectural photography. Constraints: absolutely no text, no logos, no readable product labels.
fr-stuhl|friseur/stuhl-tageslicht.jpg|1536x1024|medium|Editorial premium hair salon styling station photograph. Subject: NO PEOPLE. Setting: a single elegant styling chair in soft leather facing a large round mirror in brass frame, marble counter underneath with a few elegant hair tools neatly arranged. Lighting: natural daylight from a large window on the left. Composition: three-quarter view, depth into the salon. Color palette: aubergine wall, dusty rose accents, brass. Style: vogue beauty magazine interior photography. Constraints: absolutely no text, no logos, no readable product labels.
fr-wasch|friseur/wasch-lounge.jpg|1536x1024|medium|Editorial premium hair salon wash lounge photograph. Subject: NO PEOPLE. Setting: a sculptural ceramic wash basin with brass fixtures paired with a reclining leather chair, soft natural plants nearby. Lighting: warm low ambient pendant light. Composition: three-quarter view, depth into the salon. Color palette: aubergine wall, dusty rose accents. Style: vogue beauty magazine interior photography. Constraints: absolutely no text, no logos.
fr-coloration|friseur/coloration.jpg|1536x1024|medium|Editorial premium hair coloration detail photograph. Subject: close-up of a ceramic bowl with natural plant-based color paste and a brass-handled tinting brush on a white marble surface, a few stems of fresh herbs casually placed nearby. Lighting: warm soft side light. Composition: top-down or three-quarter angle, macro detail. Style: vogue beauty magazine editorial detail. Constraints: absolutely no text, no logos, no readable product labels, no people.
fr-brautstyling|friseur/brautstyling.jpg|1536x1024|medium|Editorial premium bridal hair styling detail photograph. Subject: an elegant low updo with intricate braids and subtle white anemone flowers and small pearl pins, viewed from behind so no face is visible, the model has soft warm brown hair. Setting: blurred salon mirror with brass frame in soft focus. Lighting: warm soft side light. Composition: detail close-up from behind. Style: vogue bridal magazine editorial. Constraints: absolutely no text, no logos, no face visible.
fr-sk1-vorher|friseur/profile-sk-1-vorher.jpg|1024x1536|medium|Editorial salon documentation portrait. Subject: a German woman in her early forties with shoulder-length brown hair showing visibly faded uneven highlights with darker root regrowth at the top, neutral natural makeup, neutral relaxed expression looking directly at the camera. Setting: neutral salon background, plain wall. Lighting: clean natural daylight from camera right. Composition: head and shoulders portrait, three-quarter angle. Style: vogue beauty magazine before-treatment documentation portrait, photorealistic. Constraints: absolutely no text, no logos, natural skin texture.
fr-sk1-nachher|friseur/profile-sk-1-nachher.jpg|1024x1536|medium|Editorial salon documentation portrait. Subject: the same German woman in her early forties as the previous before-portrait, now with professionally lightened balayage highlights showing seamless dimensional blend with healthy shine, same shoulder-length cut, subtle confident smile looking directly at the camera. Setting: same neutral salon background. Lighting: clean natural daylight from camera right. Composition: head and shoulders portrait, three-quarter angle. Style: vogue beauty magazine after-treatment documentation portrait, photorealistic. Constraints: absolutely no text, no logos, natural skin texture.
fr-sk2-analyse|friseur/profile-sk-2-analyse.jpg|1024x1536|medium|Editorial salon scalp analysis detail photograph. Subject: a close-up of a section of healthy hair parted by a brass-handled magnification tool on a scalp, viewed from above, no face visible. Setting: neutral salon background. Lighting: clean even natural daylight. Composition: top-down macro detail. Style: premium beauty documentation editorial. Constraints: absolutely no text, no logos, no face visible.
fr-sk2-nachher|friseur/profile-sk-2-nachher.jpg|1024x1536|medium|Editorial salon documentation portrait after eight-week scalp treatment. Subject: a German woman in her mid-fifties with healthy shoulder-length brown hair showing restored shine and density, subtle natural makeup, satisfied composed expression looking directly at the camera. Setting: neutral salon background. Lighting: clean natural daylight. Composition: head and shoulders portrait. Style: vogue beauty magazine documentation portrait, photorealistic. Constraints: absolutely no text, no logos, natural skin texture.
fr-sk3-vorher|friseur/profile-sk-3-vorher.jpg|1024x1536|medium|Editorial salon documentation portrait. Subject: a German woman in her late forties with very long uneven dark brown hair showing visible split ends, no makeup, neutral expression looking directly at the camera. Setting: neutral salon background. Lighting: clean natural daylight. Composition: head and shoulders portrait. Style: vogue beauty magazine before-cut documentation portrait, photorealistic. Constraints: absolutely no text, no logos, natural skin texture.
fr-sk3-nachher|friseur/profile-sk-3-nachher.jpg|1024x1536|medium|Editorial salon documentation portrait after cut. Subject: the same German woman in her late forties as the previous before-portrait, now with a structured shoulder-length cut with subtle layers and healthy texture, subtle natural makeup, confident relaxed expression looking directly at the camera. Setting: same neutral salon background. Lighting: clean natural daylight. Composition: head and shoulders portrait. Style: vogue beauty magazine after-cut documentation portrait, photorealistic. Constraints: absolutely no text, no logos, natural skin texture.
fr-news-sommer|friseur/news-sommer-trends.jpg|1536x1024|medium|Editorial summer hair trends magazine cover style photograph. Subject: an abstract composition of light golden hair strands flowing in soft summer sun flares, a soft warm beach hat blurred in the background. No face visible. Lighting: bright warm summer light. Composition: rule of thirds, soft focus. Style: vogue summer issue editorial. Constraints: absolutely no text, no logos, no face visible.
fr-news-aveda|friseur/news-aveda.jpg|1536x1024|medium|Editorial premium plant-based hair color photograph. Subject: a hand holding a brass-handled mixing bowl with vibrant natural plant pigments in red and copper tones on a white marble surface, fresh herb sprigs casually placed nearby. Lighting: warm soft side light. Composition: three-quarter top-down angle. Style: vogue beauty magazine editorial detail. Constraints: absolutely no text, no logos, no readable product labels.
fr-news-braut|friseur/news-brautsaison.jpg|1536x1024|medium|Editorial bridal hair magazine photograph. Subject: a close-up detail of an intricate side-swept braided updo with delicate white anemones and small pearl pins, viewed from behind, no face visible, soft warm brown hair. Setting: blurred wedding salon mirror background. Lighting: soft natural daylight from a window. Composition: detail close-up from behind. Style: vogue bridal magazine editorial. Constraints: absolutely no text, no logos, no face visible.
fr-video1|friseur/video-poster-1.jpg|1536x1024|medium|Editorial documentary portrait photograph. Subject: the German hair salon owner named Laura Mueller in her mid-forties with shoulder-length warm brown hair, wearing an elegant dark forest-green apron over a white blouse, calm relaxed expression looking at the camera. Setting: blurred Aveda concept salon interior with marble and brass details. Lighting: warm soft window light. Composition: medium portrait, head and shoulders, three-quarter angle. Style: vogue beauty magazine documentary portrait, photorealistic. Constraints: absolutely no text, no logos, hair details crisp, natural skin texture.
fr-video2|friseur/video-poster-2.jpg|1536x1024|medium|Editorial documentary detail of professional hair styling tutorial. Subject: close-up of skilled hands holding a section of warm brown hair with a ceramic curling iron, brass-tipped, no face visible. Setting: blurred salon mirror with warm pendant lights in background. Lighting: warm side light. Composition: macro detail of hands and hair. Style: vogue beauty tutorial editorial. Constraints: absolutely no text, no logos, no face visible.
dd-vorher1|dachdecker/vorher-1-moos.jpg|1536x1024|medium|Documentary German residential roof before renovation photograph. Subject: NO PEOPLE. Setting: weathered terracotta tiles with heavy green moss buildup and dark discoloration patches, faded tile color. Lighting: overcast moody natural daylight. Composition: tight diagonal roof view, rule of thirds. Style: authentic documentary craftsman photography. Constraints: absolutely no text, no logos, no readable signs.
dd-nachher1|dachdecker/nachher-1-neueindeckung.jpg|1536x1024|medium|Documentary German residential roof after renovation photograph. Subject: NO PEOPLE. Setting: freshly laid bright clean terracotta tiles with crisp ridge lines and neat copper flashing details. Lighting: soft clean natural daylight. Composition: tight diagonal roof view matching the before-shot angle, rule of thirds. Style: premium German craftsmanship documentary photography. Constraints: absolutely no text, no logos, no readable signs.
dd-vorher2|dachdecker/vorher-2-sturm.jpg|1536x1024|medium|Documentary German residential roof storm damage photograph. Subject: NO PEOPLE. Setting: a section of residential terracotta tile roof with several displaced and cracked tiles after a storm, visible underlayment in places, debris on roof. Lighting: overcast moody daylight after storm. Composition: tight roof view, rule of thirds. Style: authentic documentary photography. Constraints: absolutely no text, no logos.
dd-nachher2|dachdecker/nachher-2-repariert.jpg|1536x1024|medium|Documentary German residential roof after storm repair photograph. Subject: NO PEOPLE. Setting: same roof section now neatly repaired with seamlessly matched new terracotta tiles. Lighting: soft warm daylight after the storm has cleared. Composition: same angle as the storm-damage shot. Style: premium German craftsmanship documentary photography. Constraints: absolutely no text, no logos.
dd-vorher3|dachdecker/vorher-3-pv-leer.jpg|1536x1024|medium|Documentary German residential south-facing roof photograph before solar installation. Subject: NO PEOPLE. Setting: a clean expanse of terracotta tile roof prepared for solar installation. Lighting: soft daylight. Composition: roof view from below diagonal. Style: documentary photography. Constraints: absolutely no text, no logos.
dd-nachher3|dachdecker/nachher-3-pv-indach.jpg|1536x1024|medium|Documentary German residential roof after in-roof photovoltaic installation photograph. Subject: NO PEOPLE. Setting: integrated in-roof black photovoltaic panels seamlessly flush with terracotta tiles. Lighting: warm golden hour light. Composition: same angle as the before-PV shot. Style: premium German craftsmanship documentary photography. Constraints: absolutely no text, no logos, no readable brand on panels.
dd-drohne|dachdecker/drohne-poster.jpg|1536x1024|medium|Aerial drone documentary photograph of Stuttgart residential rooftops at golden hour. Subject: a patchwork of terracotta tile rooftops viewed from directly above, varied tile patterns, chimneys, occasional skylights. Lighting: warm low golden hour light casting long shadows. Composition: top-down or slight tilt, rule of thirds. Style: premium documentary aerial photography. Constraints: absolutely no text, no logos, no readable signs.
dd-video1|dachdecker/video-poster-1.jpg|1536x1024|medium|Documentary editorial detail of German craftsman work on roof. Subject: close-up of weathered hands installing a terracotta tile, hammer and slate tools nearby, no face visible. Setting: roof tile surface, blurred Stuttgart sky in background. Lighting: soft daylight. Composition: macro detail. Style: premium documentary craftsmanship editorial. Constraints: absolutely no text, no logos, no face visible.
dd-video2|dachdecker/video-poster-2.jpg|1536x1024|medium|Documentary editorial detail of fresh copper gutter installation. Subject: close-up of skilled hands shaping copper gutter with tin snips, the freshly cut copper showing warm orange tone, no face visible. Setting: roof edge, blurred residential context. Lighting: soft natural daylight. Composition: macro detail. Style: premium documentary craftsmanship editorial. Constraints: absolutely no text, no logos, no face visible.
px-empfang|praxis/empfang.jpg|1536x1024|medium|Editorial modern medical practice reception area photograph. Subject: NO PEOPLE. Setting: a bright minimalist reception desk in light oak veneer with subtle teal accents and a small monstera plant. Lighting: warm natural daylight from large windows. Composition: three-quarter view, blurred warm waiting area behind. Color palette: clean blue, soft teal, warm neutrals. Style: premium healthcare magazine architectural photography. Constraints: absolutely no text, no logos, no readable signs, no name plates.
px-warte|praxis/wartezimmer.jpg|1536x1024|medium|Editorial modern medical practice waiting room photograph. Subject: NO PEOPLE. Setting: comfortable upholstered chairs in soft beige fabric arranged around a low oak side table with a tasteful neutral magazine, large windows showing soft green outdoor view, a few indoor plants. Lighting: warm natural daylight. Composition: wide interior shot, calming neutral palette. Color palette: warm beige, soft teal, oak. Style: premium healthcare magazine interior photography. Constraints: absolutely no text, no logos, no readable signs on the magazine.
px-behand|praxis/behandlungszimmer.jpg|1536x1024|medium|Editorial modern medical practice examination room photograph. Subject: NO PEOPLE. Setting: a clean examination bed with crisp white linen, a modern wooden cabinet with neatly arranged supplies, a large window on the side. Lighting: soft natural daylight from window. Composition: three-quarter interior view. Color palette: white, soft teal, warm wood. Style: premium healthcare magazine interior photography. Constraints: absolutely no text, no logos, no readable medication labels.
px-ekg|praxis/ekg-raum.jpg|1536x1024|medium|Editorial modern medical practice diagnostic room photograph. Subject: NO PEOPLE. Setting: a modern ECG monitor on a clean white cart next to an examination bed with neat white linen, a window with soft natural light. Lighting: clean daylight. Composition: three-quarter interior view. Color palette: white, soft teal, neutral. Style: premium healthcare magazine interior photography. Constraints: absolutely no text, no logos, no readable screen content.
px-labor|praxis/labor.jpg|1536x1024|medium|Editorial modern medical practice laboratory photograph. Subject: NO PEOPLE. Setting: a clean white countertop with a modern centrifuge, microscope, and a few neatly arranged sample vials. Lighting: bright clean overhead lighting. Composition: three-quarter angle. Color palette: white, stainless steel, soft teal. Style: premium healthcare magazine interior photography. Constraints: absolutely no text, no logos, no readable vial labels.
px-news-grippe|praxis/news-grippe.jpg|1536x1024|medium|Editorial medical magazine theme photograph. Subject: an abstract clean composition of a vaccination preparation on a white surface, a glass vial blurred and a sterile syringe in the foreground, neutral cool light. Lighting: soft daylight, clean. Composition: macro detail, shallow depth of field. Style: premium healthcare editorial. Constraints: absolutely no text, no logos, no readable labels on vial.
px-news-erk|praxis/news-erkaeltung.jpg|1536x1024|medium|Editorial medical magazine seasonal cold and wellness theme photograph. Subject: a ceramic mug of warm tea with a fresh lemon slice and a small ginger root piece on a wooden surface near a softly blurred home window. Lighting: warm autumn daylight from window. Composition: three-quarter angle, cozy mood. Style: premium healthcare wellness editorial. Constraints: absolutely no text, no logos.
px-news-reise|praxis/news-reisemedizin.jpg|1536x1024|medium|Editorial medical magazine travel medicine theme photograph. Subject: an abstract composition of a vintage globe, a modern leather passport wallet and a folded linen scarf on a neutral surface. Lighting: soft natural light. Composition: three-quarter top-down. Style: premium editorial. Constraints: absolutely no text, no logos, no readable passport details.
rs-carpaccio|restaurant/menu-carpaccio.jpg|1024x1024|medium|Editorial fine dining food photograph of colorful golden and red beetroot carpaccio plated on a dark matte ceramic plate, garnished with microgreens, goat cheese crumbles, a few drops of olive oil and balsamic reduction. Lighting: warm pendant light from above. Composition: top-down angle, plate centered. Style: premium gastronomy magazine food photography. Constraints: absolutely no text, no logos.
rs-tatar|restaurant/menu-tatar.jpg|1024x1024|medium|Editorial fine dining food photograph of premium beef tartare formed in a perfect cylinder on a dark ceramic plate, topped with a glossy quail egg yolk, finely chopped chives, capers and shallots around. Lighting: warm pendant light from above. Composition: three-quarter angle. Style: premium gastronomy magazine food photography. Constraints: absolutely no text, no logos.
rs-suppe|restaurant/menu-suppe.jpg|1024x1024|medium|Editorial fine dining food photograph of creamy seasonal pumpkin soup in a dark stoneware bowl with a swirl of truffle oil and toasted pumpkin seeds on top. Lighting: warm pendant light from above. Composition: top-down angle. Style: premium gastronomy magazine food photography. Constraints: absolutely no text, no logos.
rs-lachs|restaurant/menu-lachs.jpg|1024x1024|medium|Editorial fine dining food photograph of pan-seared salmon fillet with crispy golden skin resting on a bed of wilted spinach with a foam of lemon and dill on a dark ceramic plate. Lighting: warm pendant light. Composition: three-quarter angle. Style: premium gastronomy magazine food photography. Constraints: absolutely no text, no logos.
rs-schmor|restaurant/menu-schmorbraten.jpg|1024x1024|medium|Editorial fine dining food photograph of Bavarian braised beef shoulder sliced and glazed with red wine jus on a dark ceramic plate with seasonal root vegetables and a sprig of rosemary. Lighting: warm pendant light. Composition: three-quarter angle. Style: premium gastronomy magazine food photography. Constraints: absolutely no text, no logos.
rs-schnitzel|restaurant/menu-schnitzel.jpg|1024x1024|medium|Editorial fine dining food photograph of a perfectly golden Wiener Schnitzel on a white porcelain plate with a lemon wedge, fresh parsley sprig and a small portion of parsley potatoes, classical presentation. Lighting: warm pendant light. Composition: three-quarter angle. Style: premium gastronomy magazine food photography. Constraints: absolutely no text, no logos.
rs-risotto|restaurant/menu-risotto.jpg|1024x1024|medium|Editorial fine dining food photograph of creamy saffron risotto in a wide dark ceramic plate, topped with delicate parmesan curls, a small rosemary sprig and a drizzle of olive oil. Lighting: warm pendant light. Composition: top-down angle. Style: premium gastronomy magazine food photography. Constraints: absolutely no text, no logos.
rs-fisch|restaurant/menu-fisch.jpg|1024x1024|medium|Editorial fine dining food photograph of pan-roasted whitefish fillet with herb butter and seasonal vegetables (white asparagus and morels) on a dark ceramic plate. Lighting: warm pendant light. Composition: three-quarter angle. Style: premium gastronomy magazine food photography. Constraints: absolutely no text, no logos.
rs-gnocchi|restaurant/menu-gnocchi.jpg|1024x1024|medium|Editorial fine dining food photograph of handmade potato gnocchi in brown butter sage sauce with parmesan curls on a dark ceramic plate. Lighting: warm pendant light. Composition: top-down angle. Style: premium gastronomy magazine food photography. Constraints: absolutely no text, no logos.
rs-ente|restaurant/menu-ente.jpg|1024x1024|medium|Editorial fine dining food photograph of sliced crispy duck breast on a dark ceramic plate with red cabbage, a single potato dumpling and a sprig of thyme. Lighting: warm pendant light. Composition: three-quarter angle. Style: premium gastronomy magazine food photography. Constraints: absolutely no text, no logos.
rs-kaiser|restaurant/menu-kaiserschmarrn.jpg|1024x1024|medium|Editorial fine dining food photograph of golden torn Kaiserschmarrn dusted with powdered sugar with a small bowl of plum compote on a dark ceramic plate. Lighting: warm pendant light. Composition: top-down angle. Style: premium gastronomy magazine food photography. Constraints: absolutely no text, no logos.
rs-sorbet|restaurant/menu-sorbet.jpg|1024x1024|medium|Editorial fine dining food photograph of vibrant raspberry sorbet quenelle on a dark ceramic plate with fresh raspberries and mint leaves. Lighting: cool light contrast against dark background. Composition: top-down angle, sharp focus on the quenelle. Style: premium gastronomy magazine food photography. Constraints: absolutely no text, no logos.
rs-haupt|restaurant/galerie-hauptraum.jpg|1536x1024|medium|Editorial premium fine dining restaurant interior photograph of the main dining room with warm wood paneling, copper pendant lights overhead, white linen tables with candles, intimate atmosphere. Subject: NO PEOPLE. Lighting: warm pendant glow with candle warmth. Composition: wide interior view, rule of thirds. Color palette: espresso wood, copper, off-white. Style: premium gastronomy magazine interior. Constraints: absolutely no text, no logos.
rs-tisch|restaurant/galerie-tisch.jpg|1536x1024|medium|Editorial premium restaurant table detail photograph. Subject: NO PEOPLE. Setting: white linen tablecloth with polished silver cutlery, crystal glassware, a single tapered candle in a brass holder. Lighting: warm pendant light. Composition: three-quarter table detail. Style: premium gastronomy magazine editorial. Constraints: absolutely no text, no logos.
rs-wein|restaurant/galerie-weinkarte.jpg|1536x1024|medium|Editorial premium restaurant wine cellar detail photograph. Subject: NO PEOPLE. Setting: dark wood wine racks with rows of vintage wine bottles, soft amber accent lighting on the bottles. Lighting: warm amber accent light. Composition: depth into wine rack, rule of thirds. Style: premium gastronomy magazine editorial. Constraints: absolutely no text, no logos, no readable wine labels.
rs-kueche|restaurant/galerie-kueche.jpg|1536x1024|medium|Editorial premium fine dining restaurant kitchen photograph. Subject: NO PEOPLE. Setting: stainless steel work surfaces, copper pans hanging neatly, pendant lights overhead. Lighting: warm pendant light with cooler accent. Composition: depth into kitchen. Style: premium gastronomy magazine editorial. Constraints: absolutely no text, no logos, no readable text on equipment.
rs-terr|restaurant/galerie-terrasse.jpg|1536x1024|medium|Editorial premium restaurant terrace evening photograph. Subject: NO PEOPLE. Setting: intimate outdoor dining tables with string lights and brass lanterns, blurred Munich evening city lights in the background. Lighting: warm cozy evening lights. Composition: rule of thirds, depth into the terrace. Style: premium gastronomy magazine editorial. Constraints: absolutely no text, no logos.
rs-detail|restaurant/galerie-detail.jpg|1536x1024|medium|Editorial premium restaurant interior detail photograph. Subject: NO PEOPLE. Setting: close-up of a brass wall sconce against dark wood paneling, warm glow. Lighting: warm low light. Composition: macro detail. Style: premium gastronomy magazine editorial. Constraints: absolutely no text, no logos.
sn-vorher1|sanitaer/vorher-1-bad.jpg|1536x1024|medium|Documentary outdated German bathroom before renovation photograph. Subject: NO PEOPLE. Setting: a tired 1980s bathroom with beige tile, dated chrome fixtures, an old ceramic basin and worn vinyl flooring. Lighting: fluorescent overhead light. Composition: wide interior. Style: authentic documentary photography. Constraints: absolutely no text, no logos.
sn-nachher1|sanitaer/nachher-1-bad.jpg|1536x1024|medium|Editorial premium modern German bathroom after renovation photograph. Subject: NO PEOPLE. Setting: large-format porcelain tiles in warm gray, walk-in shower with chrome fixtures, a floating oak vanity with a single ceramic basin, neatly folded towels. Lighting: soft natural daylight from window. Composition: wide interior. Style: premium handwerker magazine interior. Constraints: absolutely no text, no logos.
sn-vorher2|sanitaer/vorher-2-oelheizung.jpg|1536x1024|medium|Documentary photograph of an outdated German residential basement oil heating system from the 1990s. Subject: NO PEOPLE. Setting: a weathered green oil tank and an old white boiler with dated piping, dim basement lighting. Lighting: dim cool basement light. Composition: three-quarter view. Style: authentic documentary photography. Constraints: absolutely no text, no logos.
sn-nachher2|sanitaer/nachher-2-waermepumpe.jpg|1536x1024|medium|Editorial modern photograph of a new German residential air-source heat pump installation. Subject: NO PEOPLE. Setting: a sleek white outdoor heat pump unit on a small concrete pad against a modern house exterior wall. Lighting: clean bright daylight. Composition: three-quarter angle. Style: premium handwerker magazine editorial. Constraints: absolutely no text, no logos, no readable brand.
sn-vorher3|sanitaer/vorher-3-dach.jpg|1536x1024|medium|Documentary photograph of an empty residential south-facing roof prepared for solar installation. Subject: NO PEOPLE. Setting: a clean expanse of terracotta tile roof. Lighting: soft daylight. Composition: diagonal roof view. Style: documentary photography. Constraints: absolutely no text, no logos.
sn-nachher3|sanitaer/nachher-3-pv.jpg|1536x1024|medium|Editorial premium photograph of a completed residential photovoltaic installation. Subject: NO PEOPLE. Setting: sleek black solar panels neatly aligned on a terracotta tile roof. Lighting: warm golden hour. Composition: same angle as the before-PV shot. Style: premium handwerker magazine editorial. Constraints: absolutely no text, no logos, no readable brand on panels.
lo-sattel|spedition/flotte-sattelzug.jpg|1536x1024|medium|Editorial B2B logistics photograph of a modern Mercedes-Benz Actros 40-ton semi-truck tractor with a clean white trailer parked on a Filderstadt logistics yard. Subject: NO PEOPLE. Lighting: warm golden hour. Composition: side three-quarter view, rule of thirds. Style: premium German Mittelstand corporate photography. Constraints: absolutely no text, no logos, no readable license plates, no readable signs on the truck.
lo-wechsel|spedition/flotte-wechselbruecke.jpg|1536x1024|medium|Editorial B2B logistics photograph of a swap-body truck with a detachable container body lifted on its support legs on a clean logistics yard. Subject: NO PEOPLE. Lighting: warm golden hour. Composition: three-quarter view. Style: premium German Mittelstand corporate photography. Constraints: absolutely no text, no logos, no readable license plates, no readable signs.
lo-kuehl|spedition/flotte-kuehl.jpg|1536x1024|medium|Editorial B2B logistics photograph of a refrigerated semi-trailer with a white insulated body and visible cooling unit on the roof parked at a modern logistics yard. Subject: NO PEOPLE. Lighting: warm golden hour. Composition: three-quarter view. Style: premium German Mittelstand corporate photography. Constraints: absolutely no text, no logos, no readable license plates.
lo-sprinter|spedition/flotte-sprinter.jpg|1536x1024|medium|Editorial B2B logistics photograph of a modern Mercedes-Benz Sprinter express delivery van in clean white parked at a logistics yard. Subject: NO PEOPLE. Lighting: warm golden hour. Composition: three-quarter view. Style: premium German Mittelstand corporate photography. Constraints: absolutely no text, no logos, no readable license plates.
lo-haenger|spedition/flotte-haenger.jpg|1536x1024|medium|Editorial B2B logistics photograph of a jumbo trailer combination truck with two cargo units on a modern logistics yard. Subject: NO PEOPLE. Lighting: warm golden hour. Composition: side three-quarter view. Style: premium German Mittelstand corporate photography. Constraints: absolutely no text, no logos, no readable license plates.
lo-container|spedition/flotte-container.jpg|1536x1024|medium|Editorial B2B logistics photograph of a container chassis trailer carrying an intermodal sea container on a logistics yard. Subject: NO PEOPLE. Lighting: warm golden hour. Composition: three-quarter view. Style: premium German Mittelstand corporate photography. Constraints: absolutely no text, no logos, no readable container labels.
lo-adr|spedition/flotte-adr.jpg|1536x1024|medium|Editorial B2B logistics photograph of a stainless steel ADR-certified tanker semi-truck for hazardous goods transport parked at a logistics yard. Subject: NO PEOPLE. Lighting: warm golden hour. Composition: side three-quarter view. Style: premium German Mittelstand corporate photography. Constraints: absolutely no text, no logos, no readable license plates, no readable hazard placards.
lo-elkw|spedition/flotte-elkw.jpg|1536x1024|medium|Editorial B2B logistics photograph of a modern electric Mercedes-Benz eActros heavy-duty truck in clean white with a visible charging port at a modern sustainable logistics yard. Subject: NO PEOPLE. Lighting: warm golden hour. Composition: three-quarter view. Style: premium German Mittelstand corporate photography. Constraints: absolutely no text, no logos, no readable license plates.
EOF

generate_one() {
  local key="$1" out_path="$2" size="$3" quality="$4" prompt="$5"
  local full_out="$OUT_DIR/$out_path"
  echo "[start] $key ($size $quality)"

  local response
  response=$(curl -s --no-progress-meter --max-time 180 "$ENDPOINT" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H "Content-Type: application/json" \
    -d "$(jq -n --arg p "$prompt" --arg s "$size" --arg q "$quality" '{model: "gpt-image-1", prompt: $p, size: $s, quality: $q, n: 1, output_format: "jpeg"}')")

  local err
  err=$(echo "$response" | jq -r '.error.message // empty' 2>/dev/null)
  if [ -n "$err" ]; then
    echo "[fail] $key — $err" | head -c 250
    echo
    return 1
  fi

  local b64
  b64=$(echo "$response" | jq -r '.data[0].b64_json // empty' 2>/dev/null)
  if [ -z "$b64" ] || [ "$b64" = "null" ]; then
    echo "[fail] $key — no b64"
    return 1
  fi

  echo "$b64" | base64 -d > "$full_out"
  local size_bytes
  size_bytes=$(stat -f %z "$full_out" 2>/dev/null || stat -c %s "$full_out")
  if [ "$size_bytes" -lt 5000 ]; then
    echo "[fail] $key — file too small ($size_bytes bytes)"
    rm -f "$full_out"
    return 1
  fi
  echo "[done] $key → $out_path ($size_bytes bytes)"
  return 0
}

COUNT=0
echo "$ITEMS_RAW" | while IFS='|' read -r key path size quality prompt; do
  [ -z "$key" ] && continue
  COUNT=$((COUNT+1))
  retries=0
  until generate_one "$key" "$path" "$size" "$quality" "$prompt"; do
    retries=$((retries+1))
    if [ "$retries" -ge 2 ]; then echo "[abort] $key"; break; fi
    echo "[retry $retries/2] $key — warte 10s"; sleep 10
  done
  sleep 3
done
echo "FERTIG ($COUNT Items)."
